package xevolution.vrcg.devdemov2400;


import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.BALayout;
import anywheresoftware.b4a.debug.*;

public class consts {
private static consts mostCurrent = new consts();
public static Object getObject() {
    throw new RuntimeException("Code module does not support this method.");
}
 
public anywheresoftware.b4a.keywords.Common __c = null;
public static String _datetimeformat = "";
public static String _datetimeformattime = "";
public static int _kpilast30days = 0;
public static int _kpilastmonth = 0;
public static int _kpisincebeginning = 0;
public static int _kpibetweendates = 0;
public static int _tasktype_unknown = 0;
public static int _tasktype_alert = 0;
public static int _tasktype_task = 0;
public static int _tasktype_action = 0;
public static int _nocolor = 0;
public static int _colorred = 0;
public static int _colorgreen = 0;
public static int _colorblue = 0;
public static int _coloryellow = 0;
public static int _darkgreen = 0;
public static int _colorgray = 0;
public static int _colororange = 0;
public static int _colorlightsilver = 0;
public static int _colorwhitesilverlight = 0;
public static int _colordarkgray = 0;
public static int _colorbluesoftdark = 0;
public static int _colorbluedark = 0;
public static int _colorredorange = 0;
public static int _colorciansoftlight = 0;
public static int _colorwhite = 0;
public static int _colorlightred = 0;
public static int _colorselecselected = 0;
public static int _colorselecnotselected = 0;
public static int _whitesoftdusk = 0;
public static int _whitesoftduskblue = 0;
public static int _darkgray = 0;
public static int _blacknoalpha = 0;
public static int _colormain = 0;
public static int _colormaindarker = 0;
public static int _colorsub = 0;
public static anywheresoftware.b4a.objects.drawable.CanvasWrapper.BitmapWrapper _applogo = null;
public static anywheresoftware.b4a.objects.drawable.CanvasWrapper.BitmapWrapper _companyimage = null;
public static String _appversioncodename = "";
public static String _apptitle = "";
public static String _appwebsitelink = "";
public static String _apkname = "";
public static int _logowidth = 0;
public static int _logomobileheight = 0;
public static int _logofill = 0;
public static int _cloptiontype_buttons = 0;
public static int _cloptiontype_multibuttons = 0;
public static int _cloptiontype_textedit = 0;
public static int _cloptiontype_selectionlist = 0;
public static int _arr_firstitem = 0;
public static int _arr_seconditem = 0;
public static int _arr_thirditem = 0;
public static int _arr_fourthitem = 0;
public static int _arr_fifthitem = 0;
public static int _posoption_repeat = 0;
public static int _posoption_critical = 0;
public static int _posoption_mandatory = 0;
public static int _posoption_multiop = 0;
public static int _itkey_request = 0;
public static int _itkey_object = 0;
public static int _itkey_checklist = 0;
public static int _itkey_uniquekey = 0;
public static int _itkey_tagcode = 0;
public static int _itkey_quest = 0;
public static int _item_selected = 0;
public b4a.example.dateutils _dateutils = null;
public b4a.example.encoding _encoding = null;
public b4a.example.esc_pos _esc_pos = null;
public xevolution.vrcg.devdemov2400.main _main = null;
public xevolution.vrcg.devdemov2400.starter _starter = null;
public xevolution.vrcg.devdemov2400.comms _comms = null;
public xevolution.vrcg.devdemov2400.utils _utils = null;
public xevolution.vrcg.devdemov2400.dbstructures _dbstructures = null;
public xevolution.vrcg.devdemov2400.sharecode _sharecode = null;
public xevolution.vrcg.devdemov2400.mainmenu _mainmenu = null;
public xevolution.vrcg.devdemov2400.imageedit _imageedit = null;
public xevolution.vrcg.devdemov2400.checklist3 _checklist3 = null;
public xevolution.vrcg.devdemov2400.locationservice _locationservice = null;
public xevolution.vrcg.devdemov2400.dataupdate _dataupdate = null;
public xevolution.vrcg.devdemov2400.alerts _alerts = null;
public xevolution.vrcg.devdemov2400.backgroundupdateservice _backgroundupdateservice = null;
public xevolution.vrcg.devdemov2400.barcodescanner _barcodescanner = null;
public xevolution.vrcg.devdemov2400.cameraactivity _cameraactivity = null;
public xevolution.vrcg.devdemov2400.cameraactivity_innershot _cameraactivity_innershot = null;
public xevolution.vrcg.devdemov2400.cameraactivity2 _cameraactivity2 = null;
public xevolution.vrcg.devdemov2400.checklistnew _checklistnew = null;
public xevolution.vrcg.devdemov2400.common _common = null;
public xevolution.vrcg.devdemov2400.dbutils _dbutils = null;
public xevolution.vrcg.devdemov2400.helpdescriptors _helpdescriptors = null;
public xevolution.vrcg.devdemov2400.logs _logs = null;
public xevolution.vrcg.devdemov2400.mapsactivity _mapsactivity = null;
public xevolution.vrcg.devdemov2400.newsync _newsync = null;
public xevolution.vrcg.devdemov2400.notas _notas = null;
public xevolution.vrcg.devdemov2400.objectedit _objectedit = null;
public xevolution.vrcg.devdemov2400.objects _objects = null;
public xevolution.vrcg.devdemov2400.report _report = null;
public xevolution.vrcg.devdemov2400.reportview _reportview = null;
public xevolution.vrcg.devdemov2400.requests3 _requests3 = null;
public xevolution.vrcg.devdemov2400.signaturecapture _signaturecapture = null;
public xevolution.vrcg.devdemov2400.structures _structures = null;
public xevolution.vrcg.devdemov2400.taskscl2 _taskscl2 = null;
public xevolution.vrcg.devdemov2400.types _types = null;
public xevolution.vrcg.devdemov2400.updateservice _updateservice = null;
public xevolution.vrcg.devdemov2400.user _user = null;
public xevolution.vrcg.devdemov2400.userservice _userservice = null;
public xevolution.vrcg.devdemov2400.httputils2service _httputils2service = null;
public xevolution.vrcg.devdemov2400.xuiviewsutils _xuiviewsutils = null;
}