
package xevolution.vrcg.devdemov2400;

import java.io.IOException;
import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.pc.PCBA;
import anywheresoftware.b4a.pc.RDebug;
import anywheresoftware.b4a.pc.RemoteObject;
import anywheresoftware.b4a.pc.RDebug.IRemote;
import anywheresoftware.b4a.pc.Debug;
import anywheresoftware.b4a.pc.B4XTypes.B4XClass;
import anywheresoftware.b4a.pc.B4XTypes.DeviceClass;

public class checklist3 implements IRemote{
	public static checklist3 mostCurrent;
	public static RemoteObject processBA;
    public static boolean processGlobalsRun;
    public static RemoteObject myClass;
    public static RemoteObject remoteMe;
	public checklist3() {
		mostCurrent = this;
	}
    public RemoteObject getRemoteMe() {
        return remoteMe;    
    }
    
	public static void main (String[] args) throws Exception {
		new RDebug(args[0], Integer.parseInt(args[1]), Integer.parseInt(args[2]), args[3]);
		RDebug.INSTANCE.waitForTask();

	}
    static {
        anywheresoftware.b4a.pc.RapidSub.moduleToObject.put(new B4XClass("checklist3"), "xevolution.vrcg.devdemov2400.checklist3");
	}

public boolean isSingleton() {
		return true;
	}
     public static RemoteObject getObject() {
		return myClass;
	 }

	public RemoteObject activityBA;
	public RemoteObject _activity;
    private PCBA pcBA;

	public PCBA create(Object[] args) throws ClassNotFoundException{
		processBA = (RemoteObject) args[1];
		activityBA = (RemoteObject) args[2];
		_activity = (RemoteObject) args[3];
        anywheresoftware.b4a.keywords.Common.Density = (Float)args[4];
        remoteMe = (RemoteObject) args[5];
		pcBA = new PCBA(this, checklist3.class);
        main_subs_0.initializeProcessGlobals();
		return pcBA;
	}
public static RemoteObject __c = RemoteObject.declareNull("anywheresoftware.b4a.keywords.Common");
public static RemoteObject _device = RemoteObject.declareNull("anywheresoftware.b4a.phone.Phone");
public static RemoteObject _xui = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper.XUI");
public static RemoteObject _calculate = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xeval");
public static RemoteObject _cltimestart = RemoteObject.declareNull("anywheresoftware.b4a.objects.Timer");
public static RemoteObject _lista_aclaislocal = RemoteObject.createImmutable(0);
public static RemoteObject _lista_aclaislevel = RemoteObject.createImmutable(0);
public static RemoteObject _lista_aclalevel = RemoteObject.createImmutable(0);
public static RemoteObject _lista_save2bd = RemoteObject.createImmutable(false);
public static RemoteObject _chapterslist = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _currentchapterloaded = RemoteObject.createImmutable(0);
public static RemoteObject _currenttotalchapters = RemoteObject.createImmutable(0);
public static RemoteObject _directpassthru = RemoteObject.createImmutable(false);
public static RemoteObject _dialog = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xdialog");
public static RemoteObject _readonly_features = RemoteObject.createImmutable(false);
public static RemoteObject _child_operation = RemoteObject.createImmutable(false);
public static RemoteObject _total_points = RemoteObject.createImmutable(0);
public static RemoteObject _points_result = RemoteObject.createImmutable(false);
public static RemoteObject _cla_current_state = RemoteObject.createImmutable(0);
public static RemoteObject _cla_current_page = RemoteObject.createImmutable(0);
public static RemoteObject _nonconformities = RemoteObject.createImmutable(0);
public static RemoteObject _nonconformitiestype = RemoteObject.createImmutable(false);
public static RemoteObject _report_generated = RemoteObject.createImmutable(false);
public static RemoteObject _report_file_generated = RemoteObject.createImmutable("");
public static RemoteObject _checklist_title = RemoteObject.createImmutable("");
public static RemoteObject _appldialog = RemoteObject.declareNull("anywheresoftware.b4a.agraham.dialogs.InputDialog.CustomLayoutDialog");
public static RemoteObject _global_otype = RemoteObject.createImmutable(0);
public static RemoteObject _return2task = RemoteObject.createImmutable(false);
public static RemoteObject _return2main = RemoteObject.createImmutable(false);
public static RemoteObject _clprinter = RemoteObject.declareNull("b4a.example.bt_printer");
public static RemoteObject _signature = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.signaturecapture._signaturedata");
public static RemoteObject _signcanvas = RemoteObject.declareNull("anywheresoftware.b4a.objects.drawable.CanvasWrapper");
public static RemoteObject _cllistview = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.expandedlistview");
public static RemoteObject _cl_toppanel = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _cl_toptitle = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _cl_infotoppanel = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _clataskconclusionpanel = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _paneloptionsbar1 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _changeobjectpanel = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _terminatepanel = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _labelversion = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labeldatetime = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelcopyright = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lbltitle = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper");
public static RemoteObject _pnltitle = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper");
public static RemoteObject _pnlexpanded = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper");
public static RemoteObject _liststabpanel = RemoteObject.declareNull("anywheresoftware.b4a.objects.TabStripViewPager");
public static RemoteObject _listsbuttonpauserun = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _listsbuttonclose = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _clrunning = RemoteObject.createImmutable(false);
public static RemoteObject _cl_infotoptitle = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _butcollpseexpand = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _butnotconfirm = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _butconfirm = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _pnlcurrenindex = RemoteObject.createImmutable(0);
public static RemoteObject _actionoptionspanel = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _mainlabeloptlists = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _butchecklistrunaction = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _butchecklistrunreport = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _butchecklistrunend = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _buttonuserunavailable = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _colortabpanel = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _mainlogo = RemoteObject.declareNull("anywheresoftware.b4a.objects.ImageViewWrapper");
public static RemoteObject _cl_finaltoptitle = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _imageview1 = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper");
public static RemoteObject _pnlgroupcurrenindex = RemoteObject.createImmutable(0);
public static RemoteObject _pnlgroupcurrenindexs = RemoteObject.createImmutable(0);
public static RemoteObject _fastcloseaction = RemoteObject.createImmutable(false);
public static RemoteObject _tabpagescount = RemoteObject.createImmutable(0);
public static RemoteObject _currenttab = RemoteObject.createImmutable(0);
public static RemoteObject _currentcla = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.types._requestcla");
public static RemoteObject _claitemtitle = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _claitemeditvalue = RemoteObject.declareNull("anywheresoftware.b4a.objects.FloatLabeledEditTextWrapper");
public static RemoteObject _claitemeditvaluestk = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _clabuttonoptions = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _claitembutton_1 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _claitembutton_2 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _claitem_g1 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _claitem_g2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _claitem_g3 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _claitem_g4 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _claitem_g5 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _claitem_g6 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _claitem_g7 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _loadingprocess = RemoteObject.createImmutable(false);
public static RemoteObject _claitem_v11 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _claitem_v12 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _claitem_v13 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _claitem_v14 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _claitem_v21 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _claitem_v22 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _claitem_v23 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _claitem_v24 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _clabuttonopt0 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _clabuttonopt1 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _clabuttonopt2 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _clabuttonopt3 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _clabuttonopt4 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _clabuttonopt5 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _clabuttonopt6 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _clabuttonopt7 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _clabuttonopt8 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _clabuttonopt9 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _clabuttonopt14 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _clabuttonopt15 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _clabuttonopt16 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _clabuttonopt17 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _clabuttonopt18 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _clabuttonopt19 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _clabuttonopt20 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _clabuttonopt21 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _clabuttonopt41 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _clabuttonopt42 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _clabuttonopt43 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _clabuttonopt44 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _clabuttonopt45 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _clabuttonopt46 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _clabuttonopt47 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _clabuttonopt48 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _finresult = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _finactionbutton = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _finsignatures = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _floatlabelededittext1 = RemoteObject.declareNull("anywheresoftware.b4a.objects.FloatLabeledEditTextWrapper");
public static RemoteObject _finitemimages = RemoteObject.declareNull("b4a.example3.customlistview");
public static RemoteObject _fingroups = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.expandedlistview");
public static RemoteObject _finpause = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _finduration = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _finend = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _finstart = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _finpoints = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _claitemselectvalue = RemoteObject.declareNull("anywheresoftware.b4a.objects.SpinnerWrapper");
public static RemoteObject _claitemlabel = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _selectoptionpanel = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _buttonactionpause = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _signpanel = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _panelsignature = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _btnsavesign = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _btnclearsign = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _claitemrulervalue = RemoteObject.declareNull("anywheresoftware.b4a.objects.SeekBarWrapper");
public static RemoteObject _liststabpanelexec = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _liststabpanelobject = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _liststabpanelterminate = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _innerliststabpanelexec = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _innerliststabpanelobject = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _innerliststabpanelterminate = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _claitemrulervaluemin = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _claitemrulervaluemax = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _claitemrulervaluecurrent = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _imageselectedonreport = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _showimage = RemoteObject.declareNull("anywheresoftware.b4a.objects.ImageViewWrapper");
public static RemoteObject _imagefilename = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _imagestate = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _imageselected = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _tabbuttonchangeterminate = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _tabbuttonchangeobject = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _tabbuttonchangechecklist = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _exectabbuttonchangeterminate = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _exectabbuttonchangeobject = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _exectabbuttonchangechecklist = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _objecttabbuttonchangeterminate = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _objecttabbuttonchangeobject = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _objecttabbuttonchangechecklist = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _butchecklistreport = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _butchecklistsendreport = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _signperson = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _currentsignature = RemoteObject.createImmutable(0);
public static RemoteObject _lblgrouptitle = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _butgroupcollpseexpand = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _pnlgroupexpanded = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _pnlgrouptitle = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _objectimage = RemoteObject.declareNull("anywheresoftware.b4a.objects.ImageViewWrapper");
public static RemoteObject _objectlistview = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.expandedlistview");
public static RemoteObject _objectnotes = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _objecttagcode = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _objecttype = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _objectcode = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _button2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _button5 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _lbladdresstype = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lbladdressname = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _butaddressedit = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _lbladdressname2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lbladdresspostalcode = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lbladdresscity = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lbladdresslatitude = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lbladdresslongitude = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _butaddressmap = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _lblcontactname = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _butcontactedit = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _lbltypecontact = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lblcontactemail = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lblcontactphone = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lblpropertyvalue = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _butpropertyedit = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _lblpropertyname = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _pnlgroupexpandedprop = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lblgrouptitleprop = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _butgroupcollpseexpandprop = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _pnlgrouptitleprop = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _pnlgroupexpanded4 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lblgrouplinename = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _buttonappnetwork = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _mainactiveuser = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _currentresult = RemoteObject.createImmutable("");
public static RemoteObject _signatureexists = RemoteObject.createImmutable(0);
public static RemoteObject _claitembutton_3 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _claitembutton_4 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _claitembutton_5 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _clamandatory = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _clacritical = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _claitemdateeditvalue = RemoteObject.declareNull("anywheresoftware.b4a.objects.FloatLabeledEditTextWrapper");
public static RemoteObject _currentdateedit = RemoteObject.declareNull("anywheresoftware.b4a.objects.FloatLabeledEditTextWrapper");
public static RemoteObject _currenttimeedit = RemoteObject.declareNull("anywheresoftware.b4a.objects.FloatLabeledEditTextWrapper");
public static RemoteObject _claitemtimeeditvalue = RemoteObject.declareNull("anywheresoftware.b4a.objects.FloatLabeledEditTextWrapper");
public static RemoteObject _dlgasdetails = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _dlgasemailssubject = RemoteObject.declareNull("anywheresoftware.b4a.objects.FloatLabeledEditTextWrapper");
public static RemoteObject _dlgasemailscc = RemoteObject.declareNull("anywheresoftware.b4a.objects.FloatLabeledEditTextWrapper");
public static RemoteObject _dlgasemails = RemoteObject.declareNull("anywheresoftware.b4a.objects.FloatLabeledEditTextWrapper");
public static RemoteObject _claitembutton_6 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _butmoreleft = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _butaddmore = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _butmoreright = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _mainobservations = RemoteObject.createImmutable("");
public static RemoteObject _showimageview = RemoteObject.declareNull("anywheresoftware.b4a.objects.ImageViewWrapper");
public static RemoteObject _claitemtitleinfo = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _finalobs = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _labelmore = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _cla_terminate_click = RemoteObject.createImmutable(0);
public static RemoteObject _butassociateobject = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _noobjectpanel = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _listitemslist = RemoteObject.declareNull("b4a.example3.customlistview");
public static RemoteObject _panelclaeditoptions = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _claitemeditvaluestd = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _claitemeditvaluestdup = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _claitemeditvaluestddown = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _imagestatename = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _currententity = RemoteObject.createImmutable("");
public static RemoteObject _currentorientation = RemoteObject.createImmutable(0);
public static RemoteObject _layoutname = RemoteObject.createImmutable("");
public static RemoteObject _deviceheight = RemoteObject.createImmutable(0);
public static RemoteObject _deviceheight2 = RemoteObject.createImmutable(0);
public static RemoteObject _isphonedevice = RemoteObject.createImmutable(false);
public static RemoteObject _lblicon = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _currentfilter = RemoteObject.createImmutable("");
public static RemoteObject _pressedanswertagcode = RemoteObject.createImmutable("");
public static RemoteObject _claitemeditvalueup = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _claitemeditvaluedown = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _evcsqlgettaskitemvalue = RemoteObject.createImmutable("");
public static RemoteObject _claobjectclear = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _claobjectfind = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _claobjectlist = RemoteObject.declareNull("b4a.example3.customlistview");
public static RemoteObject _claobjecttypespinner = RemoteObject.declareNull("anywheresoftware.b4a.objects.SpinnerWrapper");
public static RemoteObject _claobjectgroupspinner = RemoteObject.declareNull("anywheresoftware.b4a.objects.SpinnerWrapper");
public static RemoteObject _claobjectdesc = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _obj_types = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _obj_groups = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _lbllineheader = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _createobjectpanel = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _createobjectcancelbutton = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _objecttypelistview = RemoteObject.declareNull("b4a.example3.customlistview");
public static RemoteObject _createobjectconfirmbutton = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _lblgroupobjecttitle = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _createobjectsavebutton = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _createobjectcancelbutton2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _objectdetailspanel = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _objecttypepanel = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _objectcreatelistview = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.customlistviewcollapse");
public static RemoteObject _selectedobjecttypetagcode = RemoteObject.createImmutable("");
public static RemoteObject _selectobjectpanel = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _suggestobjectbutton = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _cancelselectobjectbutton = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _objectslistindex = RemoteObject.createImmutable(0);
public static RemoteObject _objectexists = RemoteObject.createImmutable(false);
public static RemoteObject _signaturerequest = RemoteObject.createImmutable(0);
public static RemoteObject _signaturerequestlist = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _signaturerequestlistposis = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _btncancelsign = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _currenteditvaluefloat = RemoteObject.declareNull("anywheresoftware.b4a.objects.FloatLabeledEditTextWrapper");
public static RemoteObject _currenttimevaluefloat = RemoteObject.declareNull("anywheresoftware.b4a.objects.FloatLabeledEditTextWrapper");
public static RemoteObject _mainobjecttagcode = RemoteObject.createImmutable("");
public static RemoteObject _googlemaps = RemoteObject.declareNull("anywheresoftware.b4a.objects.MapFragmentWrapper.GoogleMapWrapper");
public static RemoteObject _dialogmap = RemoteObject.declareNull("anywheresoftware.b4a.objects.MapFragmentWrapper");
public static RemoteObject _rp = RemoteObject.declareNull("anywheresoftware.b4a.objects.RuntimePermissions");
public static RemoteObject _nonclick = RemoteObject.createImmutable(0);
public static RemoteObject _isfirstchapter = RemoteObject.createImmutable(false);
public static RemoteObject _claitemeditvalueextra = RemoteObject.declareNull("anywheresoftware.b4a.objects.FloatLabeledEditTextWrapper");
public static RemoteObject _butdessociateobject = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _butchangeobject = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _labelseleccioneobjecto = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _databulkupload = RemoteObject.createImmutable(0);
public static RemoteObject _lbltemposexecucao = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lblinicio = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lblfim = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lblduracao = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lblpausa = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lblresultado = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lbltotal = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelgrupo = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labeltipoobjecto = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labeldescritivo = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelreferenciaobjecto = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelobsobjecto = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelcodigointernobjecto = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labeltitulotipoobjecto = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelimagemobjecto = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelescolhatipoobjecto = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _itemaddress_tipomorada = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _itemaddress_endereco = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _itemaddress_continua = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _itemaddress_cpostal = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _itemaddress_latitude = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _itemaddress_longitude = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _itemaddress_localidade = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _claiteminformation = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _claitemeditvalueplus = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _claitemeditvalueminus = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _cla_stocktitle = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _cla_stock = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _clabuttonedittext = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _claitemedittextvalue = RemoteObject.declareNull("anywheresoftware.b4a.objects.FloatLabeledEditTextWrapper");
public static RemoteObject _butchecklistprinter = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _macaddress = RemoteObject.createImmutable("");
public static RemoteObject _mandatoryvalues = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _componentlist = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _b4xsbuttonslist = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _updated_inner_fields = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _updated_edit_fields = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _maineditfocuscomponent = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _butaddless = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _timeactivitystart = RemoteObject.createImmutable("");
public static RemoteObject _timeactivityend = RemoteObject.createImmutable("");
public static RemoteObject _timeactivityclstart = RemoteObject.createImmutable("");
public static RemoteObject _timeactivityclend = RemoteObject.createImmutable("");
public static RemoteObject _clabuttonsearchtext = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _listoftextviews = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _listreturnedfromquery = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _clashowonlyiteminformation = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lbldialogooutrostitle = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _txtdialogooutros = RemoteObject.declareNull("anywheresoftware.b4a.objects.FloatLabeledEditTextWrapper");
public static RemoteObject _chkdialogooutrosbd = RemoteObject.declareNull("anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper");
public static RemoteObject _buttonrulerna = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _currentbuttonna = RemoteObject.createImmutable(false);
public static RemoteObject _seekbarhasna = RemoteObject.createImmutable(false);
public static RemoteObject _object2update = RemoteObject.createImmutable("");
public static RemoteObject _butbarcode = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _runfrombarcode = RemoteObject.createImmutable(false);
public static RemoteObject _buttonfrombarcode = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _listofmandatoryitems = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _listboxextendedformat = RemoteObject.createImmutable(false);
public static RemoteObject _maindatastart = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.types._requestcla");
public static RemoteObject _startnewway = RemoteObject.createImmutable(false);
public static RemoteObject _iconextrainfo = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _dialogo_texto_extrainfo = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _currentbuttonstate = RemoteObject.createImmutable(0);
public static RemoteObject _lasteditboxfocus = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper");
public static RemoteObject _invertenablestate = RemoteObject.createImmutable(false);
public static RemoteObject _dateutils = RemoteObject.declareNull("b4a.example.dateutils");
public static RemoteObject _encoding = RemoteObject.declareNull("b4a.example.encoding");
public static RemoteObject _esc_pos = RemoteObject.declareNull("b4a.example.esc_pos");
public static xevolution.vrcg.devdemov2400.main _main = null;
public static xevolution.vrcg.devdemov2400.starter _starter = null;
public static xevolution.vrcg.devdemov2400.comms _comms = null;
public static xevolution.vrcg.devdemov2400.utils _utils = null;
public static xevolution.vrcg.devdemov2400.dbstructures _dbstructures = null;
public static xevolution.vrcg.devdemov2400.sharecode _sharecode = null;
public static xevolution.vrcg.devdemov2400.mainmenu _mainmenu = null;
public static xevolution.vrcg.devdemov2400.imageedit _imageedit = null;
public static xevolution.vrcg.devdemov2400.locationservice _locationservice = null;
public static xevolution.vrcg.devdemov2400.dataupdate _dataupdate = null;
public static xevolution.vrcg.devdemov2400.alerts _alerts = null;
public static xevolution.vrcg.devdemov2400.backgroundupdateservice _backgroundupdateservice = null;
public static xevolution.vrcg.devdemov2400.barcodescanner _barcodescanner = null;
public static xevolution.vrcg.devdemov2400.cameraactivity _cameraactivity = null;
public static xevolution.vrcg.devdemov2400.cameraactivity_innershot _cameraactivity_innershot = null;
public static xevolution.vrcg.devdemov2400.cameraactivity2 _cameraactivity2 = null;
public static xevolution.vrcg.devdemov2400.checklistnew _checklistnew = null;
public static xevolution.vrcg.devdemov2400.common _common = null;
public static xevolution.vrcg.devdemov2400.consts _consts = null;
public static xevolution.vrcg.devdemov2400.dbutils _dbutils = null;
public static xevolution.vrcg.devdemov2400.helpdescriptors _helpdescriptors = null;
public static xevolution.vrcg.devdemov2400.logs _logs = null;
public static xevolution.vrcg.devdemov2400.mapsactivity _mapsactivity = null;
public static xevolution.vrcg.devdemov2400.newsync _newsync = null;
public static xevolution.vrcg.devdemov2400.notas _notas = null;
public static xevolution.vrcg.devdemov2400.objectedit _objectedit = null;
public static xevolution.vrcg.devdemov2400.objects _objects = null;
public static xevolution.vrcg.devdemov2400.report _report = null;
public static xevolution.vrcg.devdemov2400.reportview _reportview = null;
public static xevolution.vrcg.devdemov2400.requests3 _requests3 = null;
public static xevolution.vrcg.devdemov2400.signaturecapture _signaturecapture = null;
public static xevolution.vrcg.devdemov2400.structures _structures = null;
public static xevolution.vrcg.devdemov2400.taskscl2 _taskscl2 = null;
public static xevolution.vrcg.devdemov2400.types _types = null;
public static xevolution.vrcg.devdemov2400.updateservice _updateservice = null;
public static xevolution.vrcg.devdemov2400.user _user = null;
public static xevolution.vrcg.devdemov2400.userservice _userservice = null;
public static xevolution.vrcg.devdemov2400.httputils2service _httputils2service = null;
public static xevolution.vrcg.devdemov2400.xuiviewsutils _xuiviewsutils = null;
  public Object[] GetGlobals() {
		return new Object[] {"ActionOptionsPanel",checklist3.mostCurrent._actionoptionspanel,"Activity",checklist3.mostCurrent._activity,"Alerts",Debug.moduleToString(xevolution.vrcg.devdemov2400.alerts.class),"ApplDialog",checklist3.mostCurrent._appldialog,"B4XSButtonsList",checklist3.mostCurrent._b4xsbuttonslist,"BackgroundUpdateService",Debug.moduleToString(xevolution.vrcg.devdemov2400.backgroundupdateservice.class),"BarcodeScanner",Debug.moduleToString(xevolution.vrcg.devdemov2400.barcodescanner.class),"btnCancelSign",checklist3.mostCurrent._btncancelsign,"btnClearSign",checklist3.mostCurrent._btnclearsign,"btnSaveSign",checklist3.mostCurrent._btnsavesign,"butAddLess",checklist3.mostCurrent._butaddless,"butAddMore",checklist3.mostCurrent._butaddmore,"butAddressEdit",checklist3.mostCurrent._butaddressedit,"butAddressMap",checklist3.mostCurrent._butaddressmap,"butAssociateObject",checklist3.mostCurrent._butassociateobject,"butBarCode",checklist3.mostCurrent._butbarcode,"butChangeObject",checklist3.mostCurrent._butchangeobject,"butChecklistPrinter",checklist3.mostCurrent._butchecklistprinter,"butChecklistReport",checklist3.mostCurrent._butchecklistreport,"butChecklistRunAction",checklist3.mostCurrent._butchecklistrunaction,"butChecklistRunEnd",checklist3.mostCurrent._butchecklistrunend,"butChecklistRunReport",checklist3.mostCurrent._butchecklistrunreport,"butChecklistSendReport",checklist3.mostCurrent._butchecklistsendreport,"butCollpseExpand",checklist3.mostCurrent._butcollpseexpand,"butConfirm",checklist3.mostCurrent._butconfirm,"butContactEdit",checklist3.mostCurrent._butcontactedit,"butDessociateObject",checklist3.mostCurrent._butdessociateobject,"butGroupCollpseExpand",checklist3.mostCurrent._butgroupcollpseexpand,"butGroupCollpseExpandProp",checklist3.mostCurrent._butgroupcollpseexpandprop,"butMoreLeft",checklist3.mostCurrent._butmoreleft,"butMoreRight",checklist3.mostCurrent._butmoreright,"butNotConfirm",checklist3.mostCurrent._butnotconfirm,"butPropertyEdit",checklist3.mostCurrent._butpropertyedit,"Button2",checklist3.mostCurrent._button2,"Button5",checklist3.mostCurrent._button5,"ButtonActionPause",checklist3.mostCurrent._buttonactionpause,"ButtonAppNetwork",checklist3.mostCurrent._buttonappnetwork,"ButtonFromBarcode",checklist3.mostCurrent._buttonfrombarcode,"ButtonRulerNA",checklist3.mostCurrent._buttonrulerna,"ButtonUserUnavailable",checklist3.mostCurrent._buttonuserunavailable,"calculate",checklist3._calculate,"CameraActivity",Debug.moduleToString(xevolution.vrcg.devdemov2400.cameraactivity.class),"CameraActivity_InnerShot",Debug.moduleToString(xevolution.vrcg.devdemov2400.cameraactivity_innershot.class),"CameraActivity2",Debug.moduleToString(xevolution.vrcg.devdemov2400.cameraactivity2.class),"CancelSelectObjectButton",checklist3.mostCurrent._cancelselectobjectbutton,"changeObjectPanel",checklist3.mostCurrent._changeobjectpanel,"ChaptersList",checklist3.mostCurrent._chapterslist,"CHECKLIST_TITLE",checklist3.mostCurrent._checklist_title,"CheckListNew",Debug.moduleToString(xevolution.vrcg.devdemov2400.checklistnew.class),"CHILD_OPERATION",checklist3._child_operation,"chkDialogoOutrosBD",checklist3.mostCurrent._chkdialogooutrosbd,"cl_FinaltopTitle",checklist3.mostCurrent._cl_finaltoptitle,"cl_InfotopPanel",checklist3.mostCurrent._cl_infotoppanel,"cl_InfotopTitle",checklist3.mostCurrent._cl_infotoptitle,"cl_topPanel",checklist3.mostCurrent._cl_toppanel,"cl_topTitle",checklist3.mostCurrent._cl_toptitle,"CLA_CURRENT_PAGE",checklist3._cla_current_page,"CLA_CURRENT_STATE",checklist3._cla_current_state,"CLA_Stock",checklist3.mostCurrent._cla_stock,"CLA_StockTitle",checklist3.mostCurrent._cla_stocktitle,"CLA_TERMINATE_CLICK",checklist3._cla_terminate_click,"CLAButtonEditText",checklist3.mostCurrent._clabuttonedittext,"CLAButtonOpt0",checklist3.mostCurrent._clabuttonopt0,"CLAButtonOpt1",checklist3.mostCurrent._clabuttonopt1,"CLAButtonOpt14",checklist3.mostCurrent._clabuttonopt14,"CLAButtonOpt15",checklist3.mostCurrent._clabuttonopt15,"CLAButtonOpt16",checklist3.mostCurrent._clabuttonopt16,"CLAButtonOpt17",checklist3.mostCurrent._clabuttonopt17,"CLAButtonOpt18",checklist3.mostCurrent._clabuttonopt18,"CLAButtonOpt19",checklist3.mostCurrent._clabuttonopt19,"CLAButtonOpt2",checklist3.mostCurrent._clabuttonopt2,"CLAButtonOpt20",checklist3.mostCurrent._clabuttonopt20,"CLAButtonOpt21",checklist3.mostCurrent._clabuttonopt21,"CLAButtonOpt3",checklist3.mostCurrent._clabuttonopt3,"CLAButtonOpt4",checklist3.mostCurrent._clabuttonopt4,"CLAButtonOpt41",checklist3.mostCurrent._clabuttonopt41,"CLAButtonOpt42",checklist3.mostCurrent._clabuttonopt42,"CLAButtonOpt43",checklist3.mostCurrent._clabuttonopt43,"CLAButtonOpt44",checklist3.mostCurrent._clabuttonopt44,"CLAButtonOpt45",checklist3.mostCurrent._clabuttonopt45,"CLAButtonOpt46",checklist3.mostCurrent._clabuttonopt46,"CLAButtonOpt47",checklist3.mostCurrent._clabuttonopt47,"CLAButtonOpt48",checklist3.mostCurrent._clabuttonopt48,"CLAButtonOpt5",checklist3.mostCurrent._clabuttonopt5,"CLAButtonOpt6",checklist3.mostCurrent._clabuttonopt6,"CLAButtonOpt7",checklist3.mostCurrent._clabuttonopt7,"CLAButtonOpt8",checklist3.mostCurrent._clabuttonopt8,"CLAButtonOpt9",checklist3.mostCurrent._clabuttonopt9,"CLAButtonOptions",checklist3.mostCurrent._clabuttonoptions,"CLAButtonSearchText",checklist3.mostCurrent._clabuttonsearchtext,"CLACritical",checklist3.mostCurrent._clacritical,"CLAItem_G1",checklist3.mostCurrent._claitem_g1,"CLAItem_G2",checklist3.mostCurrent._claitem_g2,"CLAItem_G3",checklist3.mostCurrent._claitem_g3,"CLAItem_G4",checklist3.mostCurrent._claitem_g4,"CLAItem_G5",checklist3.mostCurrent._claitem_g5,"CLAItem_G6",checklist3.mostCurrent._claitem_g6,"CLAItem_G7",checklist3.mostCurrent._claitem_g7,"CLAItem_V11",checklist3.mostCurrent._claitem_v11,"CLAItem_V12",checklist3.mostCurrent._claitem_v12,"CLAItem_V13",checklist3.mostCurrent._claitem_v13,"CLAItem_V14",checklist3.mostCurrent._claitem_v14,"CLAItem_V21",checklist3.mostCurrent._claitem_v21,"CLAItem_V22",checklist3.mostCurrent._claitem_v22,"CLAItem_V23",checklist3.mostCurrent._claitem_v23,"CLAItem_V24",checklist3.mostCurrent._claitem_v24,"CLAItemButton_1",checklist3.mostCurrent._claitembutton_1,"CLAItemButton_2",checklist3.mostCurrent._claitembutton_2,"CLAItemButton_3",checklist3.mostCurrent._claitembutton_3,"CLAItemButton_4",checklist3.mostCurrent._claitembutton_4,"CLAItemButton_5",checklist3.mostCurrent._claitembutton_5,"CLAItemButton_6",checklist3.mostCurrent._claitembutton_6,"CLAItemDateEditValue",checklist3.mostCurrent._claitemdateeditvalue,"CLAItemEditTextValue",checklist3.mostCurrent._claitemedittextvalue,"CLAItemEditValue",checklist3.mostCurrent._claitemeditvalue,"CLAItemEditValueDOWN",checklist3.mostCurrent._claitemeditvaluedown,"CLAItemEditValueExtra",checklist3.mostCurrent._claitemeditvalueextra,"CLAItemEditValueMINUS",checklist3.mostCurrent._claitemeditvalueminus,"CLAItemEditValuePLUS",checklist3.mostCurrent._claitemeditvalueplus,"CLAItemEditValueSTD",checklist3.mostCurrent._claitemeditvaluestd,"CLAItemEditValueSTDDOWN",checklist3.mostCurrent._claitemeditvaluestddown,"CLAItemEditValueSTDUP",checklist3.mostCurrent._claitemeditvaluestdup,"CLAItemEditValueStk",checklist3.mostCurrent._claitemeditvaluestk,"CLAItemEditValueUP",checklist3.mostCurrent._claitemeditvalueup,"CLAItemInformation",checklist3.mostCurrent._claiteminformation,"CLAItemLabel",checklist3.mostCurrent._claitemlabel,"CLAItemRulerValue",checklist3.mostCurrent._claitemrulervalue,"CLAItemRulerValueCurrent",checklist3.mostCurrent._claitemrulervaluecurrent,"CLAItemRulerValueMax",checklist3.mostCurrent._claitemrulervaluemax,"CLAItemRulerValueMin",checklist3.mostCurrent._claitemrulervaluemin,"CLAItemSelectValue",checklist3.mostCurrent._claitemselectvalue,"CLAItemTimeEditValue",checklist3.mostCurrent._claitemtimeeditvalue,"CLAItemTitle",checklist3.mostCurrent._claitemtitle,"CLAItemTitleInfo",checklist3.mostCurrent._claitemtitleinfo,"CLAMandatory",checklist3.mostCurrent._clamandatory,"CLAObjectClear",checklist3.mostCurrent._claobjectclear,"CLAObjectDesc",checklist3.mostCurrent._claobjectdesc,"CLAObjectFind",checklist3.mostCurrent._claobjectfind,"CLAObjectGroupSpinner",checklist3.mostCurrent._claobjectgroupspinner,"CLAObjectList",checklist3.mostCurrent._claobjectlist,"CLAObjectTypeSpinner",checklist3.mostCurrent._claobjecttypespinner,"CLAShowOnlyItemInformation",checklist3.mostCurrent._clashowonlyiteminformation,"ClaTaskConclusionPanel",checklist3.mostCurrent._clataskconclusionpanel,"clListView",checklist3.mostCurrent._cllistview,"CLPrinter",checklist3.mostCurrent._clprinter,"CLRunning",checklist3._clrunning,"CLTimeStart",checklist3._cltimestart,"ColorTabPanel",checklist3.mostCurrent._colortabpanel,"Common",Debug.moduleToString(xevolution.vrcg.devdemov2400.common.class),"Comms",Debug.moduleToString(xevolution.vrcg.devdemov2400.comms.class),"ComponentList",checklist3.mostCurrent._componentlist,"Consts",Debug.moduleToString(xevolution.vrcg.devdemov2400.consts.class),"createObjectCancelButton",checklist3.mostCurrent._createobjectcancelbutton,"createObjectCancelButton2",checklist3.mostCurrent._createobjectcancelbutton2,"createObjectConfirmButton",checklist3.mostCurrent._createobjectconfirmbutton,"createObjectPanel",checklist3.mostCurrent._createobjectpanel,"createObjectSaveButton",checklist3.mostCurrent._createobjectsavebutton,"CurrentButtonNA",checklist3._currentbuttonna,"CurrentButtonState",checklist3._currentbuttonstate,"CurrentChapterLoaded",checklist3._currentchapterloaded,"CurrentCLA",checklist3.mostCurrent._currentcla,"CurrentDateEdit",checklist3.mostCurrent._currentdateedit,"CurrentEditValueFloat",checklist3.mostCurrent._currenteditvaluefloat,"CurrentEntity",checklist3.mostCurrent._currententity,"CurrentFilter",checklist3.mostCurrent._currentfilter,"CurrentOrientation",checklist3._currentorientation,"CurrentResult",checklist3.mostCurrent._currentresult,"CurrentSignature",checklist3._currentsignature,"CurrentTab",checklist3._currenttab,"CurrentTimeEdit",checklist3.mostCurrent._currenttimeedit,"CurrentTimeValueFloat",checklist3.mostCurrent._currenttimevaluefloat,"CurrentTotalChapters",checklist3._currenttotalchapters,"DataBulkUpload",checklist3._databulkupload,"DataUpdate",Debug.moduleToString(xevolution.vrcg.devdemov2400.dataupdate.class),"DateUtils",checklist3.mostCurrent._dateutils,"DBStructures",Debug.moduleToString(xevolution.vrcg.devdemov2400.dbstructures.class),"DBUtils",Debug.moduleToString(xevolution.vrcg.devdemov2400.dbutils.class),"Device",checklist3._device,"DeviceHeight",checklist3._deviceheight,"DeviceHeight2",checklist3._deviceheight2,"dialog",checklist3.mostCurrent._dialog,"DialogMap",checklist3.mostCurrent._dialogmap,"dialogo_texto_extraInfo",checklist3.mostCurrent._dialogo_texto_extrainfo,"DirectPassthru",checklist3._directpassthru,"dlgASDetails",checklist3.mostCurrent._dlgasdetails,"dlgASEmails",checklist3.mostCurrent._dlgasemails,"dlgASEmailsCC",checklist3.mostCurrent._dlgasemailscc,"dlgASEmailsSubject",checklist3.mostCurrent._dlgasemailssubject,"Encoding",checklist3.mostCurrent._encoding,"ESC_POS",checklist3.mostCurrent._esc_pos,"EVCSQLGETTASKITEMVALUE",checklist3.mostCurrent._evcsqlgettaskitemvalue,"ExecTabButtonChangeChecklist",checklist3.mostCurrent._exectabbuttonchangechecklist,"ExecTabButtonChangeObject",checklist3.mostCurrent._exectabbuttonchangeobject,"ExecTabButtonChangeTerminate",checklist3.mostCurrent._exectabbuttonchangeterminate,"FastCloseAction",checklist3._fastcloseaction,"FINActionButton",checklist3.mostCurrent._finactionbutton,"FinalObs",checklist3.mostCurrent._finalobs,"FINDuration",checklist3.mostCurrent._finduration,"FINEnd",checklist3.mostCurrent._finend,"FINGroups",checklist3.mostCurrent._fingroups,"FINItemImages",checklist3.mostCurrent._finitemimages,"FINPause",checklist3.mostCurrent._finpause,"FINPoints",checklist3.mostCurrent._finpoints,"FINResult",checklist3.mostCurrent._finresult,"FINSignatures",checklist3.mostCurrent._finsignatures,"FINStart",checklist3.mostCurrent._finstart,"FloatLabeledEditText1",checklist3.mostCurrent._floatlabelededittext1,"Global_oType",checklist3._global_otype,"GoogleMaps",checklist3.mostCurrent._googlemaps,"HelpDescriptors",Debug.moduleToString(xevolution.vrcg.devdemov2400.helpdescriptors.class),"HttpUtils2Service",Debug.moduleToString(xevolution.vrcg.devdemov2400.httputils2service.class),"IconExtraInfo",checklist3.mostCurrent._iconextrainfo,"ImageEdit",Debug.moduleToString(xevolution.vrcg.devdemov2400.imageedit.class),"ImageFilename",checklist3.mostCurrent._imagefilename,"imageSelected",checklist3.mostCurrent._imageselected,"imageSelectedOnReport",checklist3.mostCurrent._imageselectedonreport,"ImageState",checklist3.mostCurrent._imagestate,"ImageStateName",checklist3.mostCurrent._imagestatename,"ImageView1",checklist3.mostCurrent._imageview1,"InnerlistsTabPanelExec",checklist3.mostCurrent._innerliststabpanelexec,"InnerlistsTabPanelObject",checklist3.mostCurrent._innerliststabpanelobject,"InnerlistsTabPanelTerminate",checklist3.mostCurrent._innerliststabpanelterminate,"InvertEnableState",checklist3._invertenablestate,"isFirstChapter",checklist3._isfirstchapter,"isPhoneDevice",checklist3._isphonedevice,"ItemAddress_Continua",checklist3.mostCurrent._itemaddress_continua,"ItemAddress_CPostal",checklist3.mostCurrent._itemaddress_cpostal,"ItemAddress_Endereco",checklist3.mostCurrent._itemaddress_endereco,"ItemAddress_Latitude",checklist3.mostCurrent._itemaddress_latitude,"ItemAddress_Localidade",checklist3.mostCurrent._itemaddress_localidade,"ItemAddress_Longitude",checklist3.mostCurrent._itemaddress_longitude,"ItemAddress_TipoMorada",checklist3.mostCurrent._itemaddress_tipomorada,"LabelCodigoInternObjecto",checklist3.mostCurrent._labelcodigointernobjecto,"LabelCopyright",checklist3.mostCurrent._labelcopyright,"LabelDateTime",checklist3.mostCurrent._labeldatetime,"LabelDescritivo",checklist3.mostCurrent._labeldescritivo,"LabelEscolhaTipoObjecto",checklist3.mostCurrent._labelescolhatipoobjecto,"LabelGrupo",checklist3.mostCurrent._labelgrupo,"LabelImagemObjecto",checklist3.mostCurrent._labelimagemobjecto,"labelMore",checklist3.mostCurrent._labelmore,"LabelObsObjecto",checklist3.mostCurrent._labelobsobjecto,"LabelReferenciaObjecto",checklist3.mostCurrent._labelreferenciaobjecto,"LabelSeleccioneObjecto",checklist3.mostCurrent._labelseleccioneobjecto,"LabelTipoObjecto",checklist3.mostCurrent._labeltipoobjecto,"LabelTituloTipoObjecto",checklist3.mostCurrent._labeltitulotipoobjecto,"LabelVersion",checklist3.mostCurrent._labelversion,"LASTEDITBOXFOCUS",checklist3.mostCurrent._lasteditboxfocus,"LayOutName",checklist3.mostCurrent._layoutname,"lblAddressCity",checklist3.mostCurrent._lbladdresscity,"lblAddressLatitude",checklist3.mostCurrent._lbladdresslatitude,"lblAddressLongitude",checklist3.mostCurrent._lbladdresslongitude,"lblAddressName",checklist3.mostCurrent._lbladdressname,"lblAddressName2",checklist3.mostCurrent._lbladdressname2,"lblAddressPostalCode",checklist3.mostCurrent._lbladdresspostalcode,"lblAddressType",checklist3.mostCurrent._lbladdresstype,"lblContactEmail",checklist3.mostCurrent._lblcontactemail,"lblContactName",checklist3.mostCurrent._lblcontactname,"lblContactPhone",checklist3.mostCurrent._lblcontactphone,"lblDialogoOutrosTitle",checklist3.mostCurrent._lbldialogooutrostitle,"lblDuracao",checklist3.mostCurrent._lblduracao,"lblFim",checklist3.mostCurrent._lblfim,"lblGroupLineName",checklist3.mostCurrent._lblgrouplinename,"lblGroupObjectTitle",checklist3.mostCurrent._lblgroupobjecttitle,"lblGroupTitle",checklist3.mostCurrent._lblgrouptitle,"lblGroupTitleProp",checklist3.mostCurrent._lblgrouptitleprop,"lblIcon",checklist3.mostCurrent._lblicon,"lblInicio",checklist3.mostCurrent._lblinicio,"lblLineHeader",checklist3.mostCurrent._lbllineheader,"lblPausa",checklist3.mostCurrent._lblpausa,"lblPropertyName",checklist3.mostCurrent._lblpropertyname,"lblPropertyValue",checklist3.mostCurrent._lblpropertyvalue,"lblResultado",checklist3.mostCurrent._lblresultado,"lblTemposExecucao",checklist3.mostCurrent._lbltemposexecucao,"lblTitle",checklist3.mostCurrent._lbltitle,"lblTotal",checklist3.mostCurrent._lbltotal,"lblTypeContact",checklist3.mostCurrent._lbltypecontact,"Lista_ACLAIsLevel",checklist3._lista_aclaislevel,"Lista_ACLAIsLocal",checklist3._lista_aclaislocal,"Lista_ACLALevel",checklist3._lista_aclalevel,"Lista_Save2BD",checklist3._lista_save2bd,"ListBoxExtendedFormat",checklist3._listboxextendedformat,"ListItemsList",checklist3.mostCurrent._listitemslist,"ListOfMandatoryItems",checklist3.mostCurrent._listofmandatoryitems,"ListOfTextViews",checklist3.mostCurrent._listoftextviews,"ListReturnedfromQuery",checklist3.mostCurrent._listreturnedfromquery,"listsButtonClose",checklist3.mostCurrent._listsbuttonclose,"listsButtonPauseRun",checklist3.mostCurrent._listsbuttonpauserun,"listsTabPanel",checklist3.mostCurrent._liststabpanel,"listsTabPanelExec",checklist3.mostCurrent._liststabpanelexec,"listsTabPanelObject",checklist3.mostCurrent._liststabpanelobject,"listsTabPanelTerminate",checklist3.mostCurrent._liststabpanelterminate,"LoadingProcess",checklist3._loadingprocess,"LocationService",Debug.moduleToString(xevolution.vrcg.devdemov2400.locationservice.class),"Logs",Debug.moduleToString(xevolution.vrcg.devdemov2400.logs.class),"MacAddress",checklist3.mostCurrent._macaddress,"Main",Debug.moduleToString(xevolution.vrcg.devdemov2400.main.class),"mainActiveUser",checklist3.mostCurrent._mainactiveuser,"MainDataStart",checklist3.mostCurrent._maindatastart,"MainEditFocusComponent",checklist3.mostCurrent._maineditfocuscomponent,"mainLabelOptLists",checklist3.mostCurrent._mainlabeloptlists,"mainLogo",checklist3.mostCurrent._mainlogo,"MainMenu",Debug.moduleToString(xevolution.vrcg.devdemov2400.mainmenu.class),"MainObjectTagCode",checklist3.mostCurrent._mainobjecttagcode,"MainObservations",checklist3.mostCurrent._mainobservations,"MandatoryValues",checklist3.mostCurrent._mandatoryvalues,"MapsActivity",Debug.moduleToString(xevolution.vrcg.devdemov2400.mapsactivity.class),"NewSync",Debug.moduleToString(xevolution.vrcg.devdemov2400.newsync.class),"NONCLICK",checklist3._nonclick,"NONCONFORMITIES",checklist3._nonconformities,"NONCONFORMITIESTYPE",checklist3._nonconformitiestype,"noObjectPanel",checklist3.mostCurrent._noobjectpanel,"notas",Debug.moduleToString(xevolution.vrcg.devdemov2400.notas.class),"OBJ_Groups",checklist3.mostCurrent._obj_groups,"OBJ_Types",checklist3.mostCurrent._obj_types,"Object2Update",checklist3.mostCurrent._object2update,"objectCode",checklist3.mostCurrent._objectcode,"objectCreateListView",checklist3.mostCurrent._objectcreatelistview,"objectDetailsPanel",checklist3.mostCurrent._objectdetailspanel,"ObjectEdit",Debug.moduleToString(xevolution.vrcg.devdemov2400.objectedit.class),"ObjectExists",checklist3._objectexists,"objectImage",checklist3.mostCurrent._objectimage,"objectListView",checklist3.mostCurrent._objectlistview,"objectNotes",checklist3.mostCurrent._objectnotes,"Objects",Debug.moduleToString(xevolution.vrcg.devdemov2400.objects.class),"ObjectsListIndex",checklist3._objectslistindex,"ObjectTabButtonChangeChecklist",checklist3.mostCurrent._objecttabbuttonchangechecklist,"ObjectTabButtonChangeObject",checklist3.mostCurrent._objecttabbuttonchangeobject,"ObjectTabButtonChangeTerminate",checklist3.mostCurrent._objecttabbuttonchangeterminate,"objectTagcode",checklist3.mostCurrent._objecttagcode,"objectType",checklist3.mostCurrent._objecttype,"ObjectTypeListView",checklist3.mostCurrent._objecttypelistview,"objectTypePanel",checklist3.mostCurrent._objecttypepanel,"PanelCLAEditOptions",checklist3.mostCurrent._panelclaeditoptions,"panelOptionsBar1",checklist3.mostCurrent._paneloptionsbar1,"PanelSignature",checklist3.mostCurrent._panelsignature,"pnlCurrenIndex",checklist3._pnlcurrenindex,"pnlExpanded",checklist3.mostCurrent._pnlexpanded,"pnlGroupCurrenIndex",checklist3._pnlgroupcurrenindex,"pnlGroupCurrenIndexs",checklist3._pnlgroupcurrenindexs,"pnlGroupExpanded",checklist3.mostCurrent._pnlgroupexpanded,"pnlGroupExpanded4",checklist3.mostCurrent._pnlgroupexpanded4,"pnlGroupExpandedProp",checklist3.mostCurrent._pnlgroupexpandedprop,"pnlGroupTitle",checklist3.mostCurrent._pnlgrouptitle,"pnlGroupTitleProp",checklist3.mostCurrent._pnlgrouptitleprop,"pnlTitle",checklist3.mostCurrent._pnltitle,"POINTS_RESULT",checklist3._points_result,"PressedAnswerTagCode",checklist3.mostCurrent._pressedanswertagcode,"READONLY_FEATURES",checklist3._readonly_features,"Report",Debug.moduleToString(xevolution.vrcg.devdemov2400.report.class),"REPORT_FILE_GENERATED",checklist3.mostCurrent._report_file_generated,"REPORT_GENERATED",checklist3._report_generated,"ReportView",Debug.moduleToString(xevolution.vrcg.devdemov2400.reportview.class),"requests3",Debug.moduleToString(xevolution.vrcg.devdemov2400.requests3.class),"Return2Main",checklist3._return2main,"Return2Task",checklist3._return2task,"rp",checklist3.mostCurrent._rp,"RunFromBarcode",checklist3._runfrombarcode,"SeekBarHasNA",checklist3._seekbarhasna,"SelectedObjectTypeTagcode",checklist3.mostCurrent._selectedobjecttypetagcode,"selectObjectPanel",checklist3.mostCurrent._selectobjectpanel,"SelectOptionPanel",checklist3.mostCurrent._selectoptionpanel,"ShareCode",Debug.moduleToString(xevolution.vrcg.devdemov2400.sharecode.class),"ShowImage",checklist3.mostCurrent._showimage,"ShowImageView",checklist3.mostCurrent._showimageview,"Signature",checklist3.mostCurrent._signature,"SignatureCapture",Debug.moduleToString(xevolution.vrcg.devdemov2400.signaturecapture.class),"SignatureExists",checklist3._signatureexists,"SignatureRequest",checklist3._signaturerequest,"SignatureRequestList",checklist3.mostCurrent._signaturerequestlist,"SignatureRequestListPosis",checklist3.mostCurrent._signaturerequestlistposis,"SignCanvas",checklist3.mostCurrent._signcanvas,"SignPanel",checklist3.mostCurrent._signpanel,"SignPerson",checklist3.mostCurrent._signperson,"Starter",Debug.moduleToString(xevolution.vrcg.devdemov2400.starter.class),"StartNewWay",checklist3._startnewway,"Structures",Debug.moduleToString(xevolution.vrcg.devdemov2400.structures.class),"suggestObjectButton",checklist3.mostCurrent._suggestobjectbutton,"TabButtonChangeChecklist",checklist3.mostCurrent._tabbuttonchangechecklist,"TabButtonChangeObject",checklist3.mostCurrent._tabbuttonchangeobject,"TabButtonChangeTerminate",checklist3.mostCurrent._tabbuttonchangeterminate,"TabPagesCount",checklist3._tabpagescount,"TasksCL2",Debug.moduleToString(xevolution.vrcg.devdemov2400.taskscl2.class),"terminatePanel",checklist3.mostCurrent._terminatepanel,"TimeActivityCLEnd",checklist3.mostCurrent._timeactivityclend,"TimeActivityCLStart",checklist3.mostCurrent._timeactivityclstart,"TimeActivityEnd",checklist3.mostCurrent._timeactivityend,"TimeActivityStart",checklist3.mostCurrent._timeactivitystart,"TOTAL_POINTS",checklist3._total_points,"txtDialogoOutros",checklist3.mostCurrent._txtdialogooutros,"Types",Debug.moduleToString(xevolution.vrcg.devdemov2400.types.class),"UPDATED_EDIT_FIELDS",checklist3.mostCurrent._updated_edit_fields,"UPDATED_INNER_FIELDS",checklist3.mostCurrent._updated_inner_fields,"UpdateService",Debug.moduleToString(xevolution.vrcg.devdemov2400.updateservice.class),"User",Debug.moduleToString(xevolution.vrcg.devdemov2400.user.class),"UserService",Debug.moduleToString(xevolution.vrcg.devdemov2400.userservice.class),"Utils",Debug.moduleToString(xevolution.vrcg.devdemov2400.utils.class),"xui",checklist3._xui,"XUIViewsUtils",Debug.moduleToString(xevolution.vrcg.devdemov2400.xuiviewsutils.class)};
}
}