package xevolution.vrcg.devdemov2400;

import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.pc.*;

public class consts_subs_0 {


public static RemoteObject  _process_globals() throws Exception{
 //BA.debugLineNum = 3;BA.debugLine="Sub Process_Globals";
 //BA.debugLineNum = 4;BA.debugLine="Public Const DateTimeFormat As String = \"yyyy-MM-";
consts._datetimeformat = BA.ObjectToString("yyyy-MM-dd");
 //BA.debugLineNum = 5;BA.debugLine="Public Const DateTimeFormatTime As String = \"HH:m";
consts._datetimeformattime = BA.ObjectToString("HH:mm:ss");
 //BA.debugLineNum = 6;BA.debugLine="Public Const KPILast30Days As Int = 0";
consts._kpilast30days = BA.numberCast(int.class, 0);
 //BA.debugLineNum = 7;BA.debugLine="Public Const KPILastMonth As Int = 1";
consts._kpilastmonth = BA.numberCast(int.class, 1);
 //BA.debugLineNum = 8;BA.debugLine="Public Const KPISinceBeginning As Int = 2";
consts._kpisincebeginning = BA.numberCast(int.class, 2);
 //BA.debugLineNum = 9;BA.debugLine="Public Const KPIBetweenDates As Int = 3";
consts._kpibetweendates = BA.numberCast(int.class, 3);
 //BA.debugLineNum = 11;BA.debugLine="Public Const TASKTYPE_UNKNOWN As Int = 0";
consts._tasktype_unknown = BA.numberCast(int.class, 0);
 //BA.debugLineNum = 12;BA.debugLine="Public Const TASKTYPE_ALERT As Int = 1";
consts._tasktype_alert = BA.numberCast(int.class, 1);
 //BA.debugLineNum = 13;BA.debugLine="Public Const TASKTYPE_TASK As Int = 2";
consts._tasktype_task = BA.numberCast(int.class, 2);
 //BA.debugLineNum = 14;BA.debugLine="Public Const TASKTYPE_ACTION As Int = 3";
consts._tasktype_action = BA.numberCast(int.class, 3);
 //BA.debugLineNum = 16;BA.debugLine="Public Const NoColor As Int = Colors.ARGB(1,255,2";
consts._nocolor = consts.mostCurrent.__c.getField(false,"Colors").runMethod(true,"ARGB",(Object)(BA.numberCast(int.class, 1)),(Object)(BA.numberCast(int.class, 255)),(Object)(BA.numberCast(int.class, 255)),(Object)(BA.numberCast(int.class, 255)));
 //BA.debugLineNum = 17;BA.debugLine="Public Const ColorRed As Int = 0xFFD13339  'Color";
consts._colorred = BA.numberCast(int.class, 0xffd13339);
 //BA.debugLineNum = 18;BA.debugLine="Public Const ColorGreen As Int = 0xFF0D893C  'Col";
consts._colorgreen = BA.numberCast(int.class, 0xff0d893c);
 //BA.debugLineNum = 19;BA.debugLine="Public Const ColorBlue As Int = 0xFF02B8C5  'Colo";
consts._colorblue = BA.numberCast(int.class, 0xff02b8c5);
 //BA.debugLineNum = 20;BA.debugLine="Public Const ColorYellow As Int = 0xFFFEBB03  'Co";
consts._coloryellow = BA.numberCast(int.class, 0xfffebb03);
 //BA.debugLineNum = 21;BA.debugLine="Public const DarkGreen As Int = 0xFF006400";
consts._darkgreen = BA.numberCast(int.class, 0xff006400);
 //BA.debugLineNum = 22;BA.debugLine="Public Const ColorGray As Int = Colors.ARGB(255,1";
consts._colorgray = consts.mostCurrent.__c.getField(false,"Colors").runMethod(true,"ARGB",(Object)(BA.numberCast(int.class, 255)),(Object)(BA.numberCast(int.class, 169)),(Object)(BA.numberCast(int.class, 169)),(Object)(BA.numberCast(int.class, 169)));
 //BA.debugLineNum = 24;BA.debugLine="Public Const ColorOrange As Int = Colors.ARGB(255";
consts._colororange = consts.mostCurrent.__c.getField(false,"Colors").runMethod(true,"ARGB",(Object)(BA.numberCast(int.class, 255)),(Object)(BA.numberCast(int.class, 255)),(Object)(BA.numberCast(int.class, 110)),(Object)(BA.numberCast(int.class, 0)));
 //BA.debugLineNum = 25;BA.debugLine="Public Const ColorLightSilver As Int = Colors.ARG";
consts._colorlightsilver = consts.mostCurrent.__c.getField(false,"Colors").runMethod(true,"ARGB",(Object)(BA.numberCast(int.class, 255)),(Object)(BA.numberCast(int.class, 220)),(Object)(BA.numberCast(int.class, 220)),(Object)(BA.numberCast(int.class, 220)));
 //BA.debugLineNum = 26;BA.debugLine="Public Const ColorWhiteSilverLight As Int = Color";
consts._colorwhitesilverlight = consts.mostCurrent.__c.getField(false,"Colors").runMethod(true,"ARGB",(Object)(BA.numberCast(int.class, 255)),(Object)(BA.numberCast(int.class, 240)),(Object)(BA.numberCast(int.class, 240)),(Object)(BA.numberCast(int.class, 240)));
 //BA.debugLineNum = 27;BA.debugLine="Public Const ColorDarkGray As Int = Colors.ARGB(2";
consts._colordarkgray = consts.mostCurrent.__c.getField(false,"Colors").runMethod(true,"ARGB",(Object)(BA.numberCast(int.class, 255)),(Object)(BA.numberCast(int.class, 50)),(Object)(BA.numberCast(int.class, 50)),(Object)(BA.numberCast(int.class, 50)));
 //BA.debugLineNum = 28;BA.debugLine="Public Const ColorBlueSoftDark As Int = Colors.AR";
consts._colorbluesoftdark = consts.mostCurrent.__c.getField(false,"Colors").runMethod(true,"ARGB",(Object)(BA.numberCast(int.class, 255)),(Object)(BA.numberCast(int.class, 240)),(Object)(BA.numberCast(int.class, 90)),(Object)(BA.numberCast(int.class, 90)));
 //BA.debugLineNum = 29;BA.debugLine="Public Const ColorBlueDark As Int = Colors.ARGB(2";
consts._colorbluedark = consts.mostCurrent.__c.getField(false,"Colors").runMethod(true,"ARGB",(Object)(BA.numberCast(int.class, 255)),(Object)(BA.numberCast(int.class, 240)),(Object)(BA.numberCast(int.class, 0)),(Object)(BA.numberCast(int.class, 0)));
 //BA.debugLineNum = 32;BA.debugLine="Public Const ColorRedOrange As Int = Colors.ARGB(";
consts._colorredorange = consts.mostCurrent.__c.getField(false,"Colors").runMethod(true,"ARGB",(Object)(BA.numberCast(int.class, 255)),(Object)(BA.numberCast(int.class, 255)),(Object)(BA.numberCast(int.class, 55)),(Object)(BA.numberCast(int.class, 0)));
 //BA.debugLineNum = 33;BA.debugLine="Public Const ColorCianSoftLight As Int = Colors.A";
consts._colorciansoftlight = consts.mostCurrent.__c.getField(false,"Colors").runMethod(true,"ARGB",(Object)(BA.numberCast(int.class, 255)),(Object)(BA.numberCast(int.class, 200)),(Object)(BA.numberCast(int.class, 230)),(Object)(BA.numberCast(int.class, 230)));
 //BA.debugLineNum = 34;BA.debugLine="Public Const ColorWhite As Int = Colors.ARGB(255,";
consts._colorwhite = consts.mostCurrent.__c.getField(false,"Colors").runMethod(true,"ARGB",(Object)(BA.numberCast(int.class, 255)),(Object)(BA.numberCast(int.class, 255)),(Object)(BA.numberCast(int.class, 255)),(Object)(BA.numberCast(int.class, 255)));
 //BA.debugLineNum = 35;BA.debugLine="Public const ColorLightRed As Int =0xFFF9D6D5";
consts._colorlightred = BA.numberCast(int.class, 0xfff9d6d5);
 //BA.debugLineNum = 36;BA.debugLine="Public Const ColorSelecSelected As Int = Colors.A";
consts._colorselecselected = consts.mostCurrent.__c.getField(false,"Colors").runMethod(true,"ARGB",(Object)(BA.numberCast(int.class, 255)),(Object)(BA.numberCast(int.class, 225)),(Object)(BA.numberCast(int.class, 255)),(Object)(BA.numberCast(int.class, 245)));
 //BA.debugLineNum = 37;BA.debugLine="Public Const ColorSelecNotSelected As Int = Color";
consts._colorselecnotselected = consts.mostCurrent.__c.getField(false,"Colors").runMethod(true,"ARGB",(Object)(BA.numberCast(int.class, 255)),(Object)(BA.numberCast(int.class, 239)),(Object)(BA.numberCast(int.class, 239)),(Object)(BA.numberCast(int.class, 239)));
 //BA.debugLineNum = 39;BA.debugLine="Public Const WhiteSoftDusk As Int = Colors.ARGB(2";
consts._whitesoftdusk = consts.mostCurrent.__c.getField(false,"Colors").runMethod(true,"ARGB",(Object)(BA.numberCast(int.class, 255)),(Object)(BA.numberCast(int.class, 240)),(Object)(BA.numberCast(int.class, 240)),(Object)(BA.numberCast(int.class, 240)));
 //BA.debugLineNum = 40;BA.debugLine="Public Const WhiteSoftDuskBlue As Int = Colors.AR";
consts._whitesoftduskblue = consts.mostCurrent.__c.getField(false,"Colors").runMethod(true,"ARGB",(Object)(BA.numberCast(int.class, 255)),(Object)(BA.numberCast(int.class, 230)),(Object)(BA.numberCast(int.class, 240)),(Object)(BA.numberCast(int.class, 250)));
 //BA.debugLineNum = 41;BA.debugLine="Public Const DarkGray As Int = Colors.ARGB(255, 8";
consts._darkgray = consts.mostCurrent.__c.getField(false,"Colors").runMethod(true,"ARGB",(Object)(BA.numberCast(int.class, 255)),(Object)(BA.numberCast(int.class, 85)),(Object)(BA.numberCast(int.class, 85)),(Object)(BA.numberCast(int.class, 85)));
 //BA.debugLineNum = 42;BA.debugLine="Public Const BlackNoAlpha As Int = Colors.ARGB(0,";
consts._blacknoalpha = consts.mostCurrent.__c.getField(false,"Colors").runMethod(true,"ARGB",(Object)(BA.numberCast(int.class, 0)),(Object)(BA.numberCast(int.class, 0)),(Object)(BA.numberCast(int.class, 0)),(Object)(BA.numberCast(int.class, 0)));
 //BA.debugLineNum = 45;BA.debugLine="Public ColorMain As Int = Colors.ARGB(255,240,0,0";
consts._colormain = consts.mostCurrent.__c.getField(false,"Colors").runMethod(true,"ARGB",(Object)(BA.numberCast(int.class, 255)),(Object)(BA.numberCast(int.class, 240)),(Object)(BA.numberCast(int.class, 0)),(Object)(BA.numberCast(int.class, 0)));
 //BA.debugLineNum = 46;BA.debugLine="Public ColorMainDarker As Int = Colors.ARGB(255,2";
consts._colormaindarker = consts.mostCurrent.__c.getField(false,"Colors").runMethod(true,"ARGB",(Object)(BA.numberCast(int.class, 255)),(Object)(BA.numberCast(int.class, 210)),(Object)(BA.numberCast(int.class, 0)),(Object)(BA.numberCast(int.class, 0)));
 //BA.debugLineNum = 47;BA.debugLine="Public ColorSub As Int = Colors.ARGB(255, 140, 0,";
consts._colorsub = consts.mostCurrent.__c.getField(false,"Colors").runMethod(true,"ARGB",(Object)(BA.numberCast(int.class, 255)),(Object)(BA.numberCast(int.class, 140)),(Object)(BA.numberCast(int.class, 0)),(Object)(BA.numberCast(int.class, 0)));
 //BA.debugLineNum = 50;BA.debugLine="Public AppLogo As Bitmap = LoadBitmap(File.DirAss";
consts._applogo = RemoteObject.createNew ("anywheresoftware.b4a.objects.drawable.CanvasWrapper.BitmapWrapper");
consts._applogo = consts.mostCurrent.__c.runMethod(false,"LoadBitmap",(Object)(consts.mostCurrent.__c.getField(false,"File").runMethod(true,"getDirAssets")),(Object)(RemoteObject.createImmutable("icon_100px.png")));
 //BA.debugLineNum = 51;BA.debugLine="Public CompanyImage As Bitmap = LoadBitmap(File.D";
consts._companyimage = RemoteObject.createNew ("anywheresoftware.b4a.objects.drawable.CanvasWrapper.BitmapWrapper");
consts._companyimage = consts.mostCurrent.__c.runMethod(false,"LoadBitmap",(Object)(consts.mostCurrent.__c.getField(false,"File").runMethod(true,"getDirAssets")),(Object)(RemoteObject.createImmutable("vrcg_business_logo.png")));
 //BA.debugLineNum = 54;BA.debugLine="Public AppVersionCodeName As String = \"Vodafone R";
consts._appversioncodename = BA.ObjectToString("Vodafone RCG v.2.01");
 //BA.debugLineNum = 55;BA.debugLine="Public AppTitle As String = \"Vodafone ReadyCheckG";
consts._apptitle = BA.ObjectToString("Vodafone ReadyCheckGo");
 //BA.debugLineNum = 56;BA.debugLine="Public AppWebSiteLink As String = \"https://www.vr";
consts._appwebsitelink = BA.ObjectToString("https://www.vrcg.pt");
 //BA.debugLineNum = 57;BA.debugLine="Public ApkName As String = \"vrcg_demo.apk\"";
consts._apkname = BA.ObjectToString("vrcg_demo.apk");
 //BA.debugLineNum = 76;BA.debugLine="Public LogoWidth As Int = 60";
consts._logowidth = BA.numberCast(int.class, 60);
 //BA.debugLineNum = 77;BA.debugLine="Public LogoMobileHeight As Int = 40";
consts._logomobileheight = BA.numberCast(int.class, 40);
 //BA.debugLineNum = 78;BA.debugLine="Public LogoFill As Int = Gravity.FILL";
consts._logofill = consts.mostCurrent.__c.getField(false,"Gravity").getField(true,"FILL");
 //BA.debugLineNum = 80;BA.debugLine="Public Const CLOptionType_Buttons As Int = 0";
consts._cloptiontype_buttons = BA.numberCast(int.class, 0);
 //BA.debugLineNum = 81;BA.debugLine="Public Const CLOptionType_MultiButtons As Int = 1";
consts._cloptiontype_multibuttons = BA.numberCast(int.class, 1);
 //BA.debugLineNum = 82;BA.debugLine="Public Const CLOptionType_TextEdit As Int = 2";
consts._cloptiontype_textedit = BA.numberCast(int.class, 2);
 //BA.debugLineNum = 83;BA.debugLine="Public Const CLOptionType_SelectionList As Int =";
consts._cloptiontype_selectionlist = BA.numberCast(int.class, 3);
 //BA.debugLineNum = 85;BA.debugLine="Public Const ARR_FIRSTITEM As Int = 0";
consts._arr_firstitem = BA.numberCast(int.class, 0);
 //BA.debugLineNum = 86;BA.debugLine="Public Const ARR_SECONDITEM As Int = 1";
consts._arr_seconditem = BA.numberCast(int.class, 1);
 //BA.debugLineNum = 87;BA.debugLine="Public Const ARR_THIRDITEM As Int = 2";
consts._arr_thirditem = BA.numberCast(int.class, 2);
 //BA.debugLineNum = 88;BA.debugLine="Public Const ARR_FOURTHITEM As Int = 3";
consts._arr_fourthitem = BA.numberCast(int.class, 3);
 //BA.debugLineNum = 89;BA.debugLine="Public Const ARR_FIFTHITEM As Int = 4";
consts._arr_fifthitem = BA.numberCast(int.class, 4);
 //BA.debugLineNum = 94;BA.debugLine="Public Const POSOPTION_REPEAT As Int = 0";
consts._posoption_repeat = BA.numberCast(int.class, 0);
 //BA.debugLineNum = 95;BA.debugLine="Public Const POSOPTION_CRITICAL As Int = 1";
consts._posoption_critical = BA.numberCast(int.class, 1);
 //BA.debugLineNum = 96;BA.debugLine="Public Const POSOPTION_MANDATORY As Int = 2";
consts._posoption_mandatory = BA.numberCast(int.class, 2);
 //BA.debugLineNum = 97;BA.debugLine="Public Const POSOPTION_MULTIOP As Int = 3";
consts._posoption_multiop = BA.numberCast(int.class, 3);
 //BA.debugLineNum = 105;BA.debugLine="Public Const ITKEY_REQUEST As Int = 0";
consts._itkey_request = BA.numberCast(int.class, 0);
 //BA.debugLineNum = 106;BA.debugLine="Public Const ITKEY_OBJECT As Int = 1";
consts._itkey_object = BA.numberCast(int.class, 1);
 //BA.debugLineNum = 107;BA.debugLine="Public Const ITKEY_CHECKLIST As Int = 2";
consts._itkey_checklist = BA.numberCast(int.class, 2);
 //BA.debugLineNum = 108;BA.debugLine="Public Const ITKEY_UNIQUEKEY As Int = 3";
consts._itkey_uniquekey = BA.numberCast(int.class, 3);
 //BA.debugLineNum = 109;BA.debugLine="Public Const ITKEY_TAGCODE As Int = 3";
consts._itkey_tagcode = BA.numberCast(int.class, 3);
 //BA.debugLineNum = 110;BA.debugLine="Public Const ITKEY_QUEST As Int = 4";
consts._itkey_quest = BA.numberCast(int.class, 4);
 //BA.debugLineNum = 113;BA.debugLine="Public Const ITEM_SELECTED As Int = 1";
consts._item_selected = BA.numberCast(int.class, 1);
 //BA.debugLineNum = 116;BA.debugLine="End Sub";
return RemoteObject.createImmutable("");
}
}