
package xevolution.vrcg.devdemov2400;

import java.io.IOException;
import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.pc.PCBA;
import anywheresoftware.b4a.pc.RDebug;
import anywheresoftware.b4a.pc.RemoteObject;
import anywheresoftware.b4a.pc.RDebug.IRemote;
import anywheresoftware.b4a.pc.Debug;
import anywheresoftware.b4a.pc.B4XTypes.B4XClass;
import anywheresoftware.b4a.pc.B4XTypes.DeviceClass;

public class objectedit implements IRemote{
	public static objectedit mostCurrent;
	public static RemoteObject processBA;
    public static boolean processGlobalsRun;
    public static RemoteObject myClass;
    public static RemoteObject remoteMe;
	public objectedit() {
		mostCurrent = this;
	}
    public RemoteObject getRemoteMe() {
        return remoteMe;    
    }
    
	public static void main (String[] args) throws Exception {
		new RDebug(args[0], Integer.parseInt(args[1]), Integer.parseInt(args[2]), args[3]);
		RDebug.INSTANCE.waitForTask();

	}
    static {
        anywheresoftware.b4a.pc.RapidSub.moduleToObject.put(new B4XClass("objectedit"), "xevolution.vrcg.devdemov2400.objectedit");
	}

public boolean isSingleton() {
		return true;
	}
     public static RemoteObject getObject() {
		return myClass;
	 }

	public RemoteObject activityBA;
	public RemoteObject _activity;
    private PCBA pcBA;

	public PCBA create(Object[] args) throws ClassNotFoundException{
		processBA = (RemoteObject) args[1];
		activityBA = (RemoteObject) args[2];
		_activity = (RemoteObject) args[3];
        anywheresoftware.b4a.keywords.Common.Density = (Float)args[4];
        remoteMe = (RemoteObject) args[5];
		pcBA = new PCBA(this, objectedit.class);
        main_subs_0.initializeProcessGlobals();
		return pcBA;
	}
public static RemoteObject __c = RemoteObject.declareNull("anywheresoftware.b4a.keywords.Common");
public static RemoteObject _device = RemoteObject.declareNull("anywheresoftware.b4a.phone.Phone");
public static RemoteObject _xui = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper.XUI");
public static RemoteObject _buttonuserunavailable = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _labelappinfo = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelcopyright = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labeldatetime = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelversion = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listsbuttonadd = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _listsbuttonclose = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _listslabelinfo = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _liststabpanel = RemoteObject.declareNull("anywheresoftware.b4a.objects.TabStripViewPager");
public static RemoteObject _mainlabeloptlists = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _objectlistview = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.customlistviewcollapse");
public static RemoteObject _objectnotes = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _objectcode = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _objecttype = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _objecttagcode = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lblcontactname = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _butcontactedit = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _lbltypecontact = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lblcontactemail = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lblcontactphone = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lbladdresstype = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lbladdressname = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lbladdressname2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lbladdresspostalcode = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lbladdresslatitude = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lbladdresslongitude = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lbladdresscity = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _butaddressmap = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _butaddressedit = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _lblpropertyvalue = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _butpropertyedit = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _lblpropertyname = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _pnlgroupexpanded = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lblgrouptitle = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _pnlcurrent = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _butgroupcollpseexpand = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _pnlgrouptitle = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _currentgroupitem = RemoteObject.createImmutable(0);
public static RemoteObject _currentgroupitemprop = RemoteObject.createImmutable(0);
public static RemoteObject _pnlgroupcurrenindex = RemoteObject.createImmutable(0);
public static RemoteObject _pnlgroupcurrenpropindex = RemoteObject.createImmutable(0);
public static RemoteObject _objectcontractname = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _objectcontractstart = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _objectcontractend = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _objectcontractdaysperiod = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _objectcontractduration = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _objectcontractdaysnotice = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _w0 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _w1 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _w2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _w3 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _w4 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _w5 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _w6 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _w7 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d1 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d3 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d4 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d5 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d6 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d7 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d8 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d9 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d10 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d11 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d12 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d13 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d14 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d15 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d16 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d17 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d18 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d19 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d20 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d30 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d29 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d28 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d27 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d26 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d25 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d24 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d23 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d22 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d21 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d31 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d32 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _d33 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _contractpanel = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _typeperiodicity = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _typedayperiod = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _butcontracttask = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _lblcontracttask = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _objectcontracthourperiod = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _objectcontracthours = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _objectcontractperiod = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _objectwhname = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _objectwhitemscheck = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.customlistviewcollapse");
public static RemoteObject _objectwhitemstaken = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.customlistviewcollapse");
public static RemoteObject _currentaddresstagcode = RemoteObject.createImmutable("");
public static RemoteObject _currentobjecttagcode = RemoteObject.createImmutable("");
public static RemoteObject _typeaddresslist = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _currentcontacttagcode = RemoteObject.createImmutable("");
public static RemoteObject _typecontactslist = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _listobjects = RemoteObject.declareNull("b4a.example3.customlistview");
public static RemoteObject _listitemreference = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listitemlocation = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _norecordspanel = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _norecordslabel = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listbutrefresh = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _listdocuments = RemoteObject.declareNull("b4a.example3.customlistview");
public static RemoteObject _listitemdocbutton = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listitemtitle = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listitemcategory = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listitemsdate = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listitemedate = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _warehousepanel = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _listitemfullname = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _objectpropertylistview = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.customlistviewcollapse");
public static RemoteObject _pnlgrouptitle2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lblgrouptitle2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _butgroupcollpseexpand2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _pnlgroupexpanded2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _butgroupcollpseexpandprop = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _lblgrouptitleprop = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _pnlcurrentprop = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _pnlgroupexpandedprop = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _pnlgrouptitleprop = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _thisobjecttype = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.types._objecttype");
public static RemoteObject _listitemtype = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listitemtodayrequests = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listbutmap = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _objrequests = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _objrequestsnottoday = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _colortabpanel = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _mainactiveuser = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _mainlogo = RemoteObject.declareNull("anywheresoftware.b4a.objects.ImageViewWrapper");
public static RemoteObject _objectslistviewpanel = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _objectsdocumentsviewpanel = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _objectdocumentsviewpanel = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _menupanelbuttonone = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _menupanelbuttomtwo = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _menupanelbuttonthree = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _menupanelbuttonfour = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _menupanelbuttonlist = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _menupanelpagestitle = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _buttononelayoutindex = RemoteObject.createImmutable(0);
public static RemoteObject _buttononelayouttwo = RemoteObject.createImmutable(0);
public static RemoteObject _buttononelayoutthree = RemoteObject.createImmutable(0);
public static RemoteObject _buttononelayoutfour = RemoteObject.createImmutable(0);
public static RemoteObject _objecteditselectedname = RemoteObject.createImmutable("");
public static RemoteObject _objectparent = RemoteObject.createImmutable("");
public static RemoteObject _panel1 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _menupanel = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _showimage = RemoteObject.declareNull("anywheresoftware.b4a.objects.ImageViewWrapper");
public static RemoteObject _imagefilename = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _imagestatename = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelobjdocsdescritivo = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelobjdocsvalidade = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labeltypeobjectfilter = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelobjvvdescritivo = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelobjvvvalidade = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelobjvvaccao = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _objgv2labeltipoobj = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _objgv2labelcodinterno = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _objgv2labelobs = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _objgv2labelref = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _itemaddress_tipomorada = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _itemaddress_endereco = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _itemaddress_continua = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _itemaddress_cpostal = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _itemaddress_latitude = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _itemaddress_longitude = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _itemaddress_localidade = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _objgv2labelrelacao = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _objparent = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _dateutils = RemoteObject.declareNull("b4a.example.dateutils");
public static RemoteObject _encoding = RemoteObject.declareNull("b4a.example.encoding");
public static RemoteObject _esc_pos = RemoteObject.declareNull("b4a.example.esc_pos");
public static xevolution.vrcg.devdemov2400.main _main = null;
public static xevolution.vrcg.devdemov2400.starter _starter = null;
public static xevolution.vrcg.devdemov2400.comms _comms = null;
public static xevolution.vrcg.devdemov2400.utils _utils = null;
public static xevolution.vrcg.devdemov2400.dbstructures _dbstructures = null;
public static xevolution.vrcg.devdemov2400.sharecode _sharecode = null;
public static xevolution.vrcg.devdemov2400.mainmenu _mainmenu = null;
public static xevolution.vrcg.devdemov2400.imageedit _imageedit = null;
public static xevolution.vrcg.devdemov2400.checklist3 _checklist3 = null;
public static xevolution.vrcg.devdemov2400.locationservice _locationservice = null;
public static xevolution.vrcg.devdemov2400.dataupdate _dataupdate = null;
public static xevolution.vrcg.devdemov2400.alerts _alerts = null;
public static xevolution.vrcg.devdemov2400.backgroundupdateservice _backgroundupdateservice = null;
public static xevolution.vrcg.devdemov2400.barcodescanner _barcodescanner = null;
public static xevolution.vrcg.devdemov2400.cameraactivity _cameraactivity = null;
public static xevolution.vrcg.devdemov2400.cameraactivity_innershot _cameraactivity_innershot = null;
public static xevolution.vrcg.devdemov2400.cameraactivity2 _cameraactivity2 = null;
public static xevolution.vrcg.devdemov2400.checklistnew _checklistnew = null;
public static xevolution.vrcg.devdemov2400.common _common = null;
public static xevolution.vrcg.devdemov2400.consts _consts = null;
public static xevolution.vrcg.devdemov2400.dbutils _dbutils = null;
public static xevolution.vrcg.devdemov2400.helpdescriptors _helpdescriptors = null;
public static xevolution.vrcg.devdemov2400.logs _logs = null;
public static xevolution.vrcg.devdemov2400.mapsactivity _mapsactivity = null;
public static xevolution.vrcg.devdemov2400.newsync _newsync = null;
public static xevolution.vrcg.devdemov2400.notas _notas = null;
public static xevolution.vrcg.devdemov2400.objects _objects = null;
public static xevolution.vrcg.devdemov2400.report _report = null;
public static xevolution.vrcg.devdemov2400.reportview _reportview = null;
public static xevolution.vrcg.devdemov2400.requests3 _requests3 = null;
public static xevolution.vrcg.devdemov2400.signaturecapture _signaturecapture = null;
public static xevolution.vrcg.devdemov2400.structures _structures = null;
public static xevolution.vrcg.devdemov2400.taskscl2 _taskscl2 = null;
public static xevolution.vrcg.devdemov2400.types _types = null;
public static xevolution.vrcg.devdemov2400.updateservice _updateservice = null;
public static xevolution.vrcg.devdemov2400.user _user = null;
public static xevolution.vrcg.devdemov2400.userservice _userservice = null;
public static xevolution.vrcg.devdemov2400.httputils2service _httputils2service = null;
public static xevolution.vrcg.devdemov2400.xuiviewsutils _xuiviewsutils = null;
  public Object[] GetGlobals() {
		return new Object[] {"Activity",objectedit.mostCurrent._activity,"Alerts",Debug.moduleToString(xevolution.vrcg.devdemov2400.alerts.class),"BackgroundUpdateService",Debug.moduleToString(xevolution.vrcg.devdemov2400.backgroundupdateservice.class),"BarcodeScanner",Debug.moduleToString(xevolution.vrcg.devdemov2400.barcodescanner.class),"butAddressEdit",objectedit.mostCurrent._butaddressedit,"butAddressMap",objectedit.mostCurrent._butaddressmap,"butContactEdit",objectedit.mostCurrent._butcontactedit,"butContractTask",objectedit.mostCurrent._butcontracttask,"butGroupCollpseExpand",objectedit.mostCurrent._butgroupcollpseexpand,"butGroupCollpseExpand2",objectedit.mostCurrent._butgroupcollpseexpand2,"butGroupCollpseExpandProp",objectedit.mostCurrent._butgroupcollpseexpandprop,"butPropertyEdit",objectedit.mostCurrent._butpropertyedit,"ButtonOneLayoutFour",objectedit._buttononelayoutfour,"ButtonOneLayoutIndex",objectedit._buttononelayoutindex,"ButtonOneLayoutThree",objectedit._buttononelayoutthree,"ButtonOneLayoutTwo",objectedit._buttononelayouttwo,"ButtonUserUnavailable",objectedit.mostCurrent._buttonuserunavailable,"CameraActivity",Debug.moduleToString(xevolution.vrcg.devdemov2400.cameraactivity.class),"CameraActivity_InnerShot",Debug.moduleToString(xevolution.vrcg.devdemov2400.cameraactivity_innershot.class),"CameraActivity2",Debug.moduleToString(xevolution.vrcg.devdemov2400.cameraactivity2.class),"CheckList3",Debug.moduleToString(xevolution.vrcg.devdemov2400.checklist3.class),"CheckListNew",Debug.moduleToString(xevolution.vrcg.devdemov2400.checklistnew.class),"ColorTabPanel",objectedit.mostCurrent._colortabpanel,"Common",Debug.moduleToString(xevolution.vrcg.devdemov2400.common.class),"Comms",Debug.moduleToString(xevolution.vrcg.devdemov2400.comms.class),"Consts",Debug.moduleToString(xevolution.vrcg.devdemov2400.consts.class),"contractPanel",objectedit.mostCurrent._contractpanel,"CurrentAddressTagcode",objectedit.mostCurrent._currentaddresstagcode,"CurrentContactTagcode",objectedit.mostCurrent._currentcontacttagcode,"CurrentGroupItem",objectedit._currentgroupitem,"CurrentGroupItemProp",objectedit._currentgroupitemprop,"CurrentobjectTagcode",objectedit.mostCurrent._currentobjecttagcode,"d1",objectedit.mostCurrent._d1,"d10",objectedit.mostCurrent._d10,"d11",objectedit.mostCurrent._d11,"d12",objectedit.mostCurrent._d12,"d13",objectedit.mostCurrent._d13,"d14",objectedit.mostCurrent._d14,"d15",objectedit.mostCurrent._d15,"d16",objectedit.mostCurrent._d16,"d17",objectedit.mostCurrent._d17,"d18",objectedit.mostCurrent._d18,"d19",objectedit.mostCurrent._d19,"d2",objectedit.mostCurrent._d2,"d20",objectedit.mostCurrent._d20,"d21",objectedit.mostCurrent._d21,"d22",objectedit.mostCurrent._d22,"d23",objectedit.mostCurrent._d23,"d24",objectedit.mostCurrent._d24,"d25",objectedit.mostCurrent._d25,"d26",objectedit.mostCurrent._d26,"d27",objectedit.mostCurrent._d27,"d28",objectedit.mostCurrent._d28,"d29",objectedit.mostCurrent._d29,"d3",objectedit.mostCurrent._d3,"d30",objectedit.mostCurrent._d30,"d31",objectedit.mostCurrent._d31,"d32",objectedit.mostCurrent._d32,"d33",objectedit.mostCurrent._d33,"d4",objectedit.mostCurrent._d4,"d5",objectedit.mostCurrent._d5,"d6",objectedit.mostCurrent._d6,"d7",objectedit.mostCurrent._d7,"d8",objectedit.mostCurrent._d8,"d9",objectedit.mostCurrent._d9,"DataUpdate",Debug.moduleToString(xevolution.vrcg.devdemov2400.dataupdate.class),"DateUtils",objectedit.mostCurrent._dateutils,"DBStructures",Debug.moduleToString(xevolution.vrcg.devdemov2400.dbstructures.class),"DBUtils",Debug.moduleToString(xevolution.vrcg.devdemov2400.dbutils.class),"Device",objectedit._device,"Encoding",objectedit.mostCurrent._encoding,"ESC_POS",objectedit.mostCurrent._esc_pos,"HelpDescriptors",Debug.moduleToString(xevolution.vrcg.devdemov2400.helpdescriptors.class),"HttpUtils2Service",Debug.moduleToString(xevolution.vrcg.devdemov2400.httputils2service.class),"ImageEdit",Debug.moduleToString(xevolution.vrcg.devdemov2400.imageedit.class),"ImageFilename",objectedit.mostCurrent._imagefilename,"ImageStateName",objectedit.mostCurrent._imagestatename,"ItemAddress_Continua",objectedit.mostCurrent._itemaddress_continua,"ItemAddress_CPostal",objectedit.mostCurrent._itemaddress_cpostal,"ItemAddress_Endereco",objectedit.mostCurrent._itemaddress_endereco,"ItemAddress_Latitude",objectedit.mostCurrent._itemaddress_latitude,"ItemAddress_Localidade",objectedit.mostCurrent._itemaddress_localidade,"ItemAddress_Longitude",objectedit.mostCurrent._itemaddress_longitude,"ItemAddress_TipoMorada",objectedit.mostCurrent._itemaddress_tipomorada,"LabelAppInfo",objectedit.mostCurrent._labelappinfo,"LabelCopyright",objectedit.mostCurrent._labelcopyright,"LabelDateTime",objectedit.mostCurrent._labeldatetime,"LabelObjDocsDescritivo",objectedit.mostCurrent._labelobjdocsdescritivo,"LabelObjDocsValidade",objectedit.mostCurrent._labelobjdocsvalidade,"LabelObjVVAccao",objectedit.mostCurrent._labelobjvvaccao,"LabelObjVVDescritivo",objectedit.mostCurrent._labelobjvvdescritivo,"LabelObjVVValidade",objectedit.mostCurrent._labelobjvvvalidade,"labelTypeObjectFilter",objectedit.mostCurrent._labeltypeobjectfilter,"LabelVersion",objectedit.mostCurrent._labelversion,"lblAddressCity",objectedit.mostCurrent._lbladdresscity,"lblAddressLatitude",objectedit.mostCurrent._lbladdresslatitude,"lblAddressLongitude",objectedit.mostCurrent._lbladdresslongitude,"lblAddressName",objectedit.mostCurrent._lbladdressname,"lblAddressName2",objectedit.mostCurrent._lbladdressname2,"lblAddressPostalCode",objectedit.mostCurrent._lbladdresspostalcode,"lblAddressType",objectedit.mostCurrent._lbladdresstype,"lblContactEmail",objectedit.mostCurrent._lblcontactemail,"lblContactName",objectedit.mostCurrent._lblcontactname,"lblContactPhone",objectedit.mostCurrent._lblcontactphone,"lblContractTask",objectedit.mostCurrent._lblcontracttask,"lblGroupTitle",objectedit.mostCurrent._lblgrouptitle,"lblGroupTitle2",objectedit.mostCurrent._lblgrouptitle2,"lblGroupTitleProp",objectedit.mostCurrent._lblgrouptitleprop,"lblPropertyName",objectedit.mostCurrent._lblpropertyname,"lblPropertyValue",objectedit.mostCurrent._lblpropertyvalue,"lblTypeContact",objectedit.mostCurrent._lbltypecontact,"listButMap",objectedit.mostCurrent._listbutmap,"listButRefresh",objectedit.mostCurrent._listbutrefresh,"listDocuments",objectedit.mostCurrent._listdocuments,"ListItemCategory",objectedit.mostCurrent._listitemcategory,"ListItemDocButton",objectedit.mostCurrent._listitemdocbutton,"ListItemEDate",objectedit.mostCurrent._listitemedate,"ListItemFullName",objectedit.mostCurrent._listitemfullname,"ListItemLocation",objectedit.mostCurrent._listitemlocation,"ListItemReference",objectedit.mostCurrent._listitemreference,"ListItemSDate",objectedit.mostCurrent._listitemsdate,"ListItemTitle",objectedit.mostCurrent._listitemtitle,"ListItemTodayRequests",objectedit.mostCurrent._listitemtodayrequests,"ListItemType",objectedit.mostCurrent._listitemtype,"listObjects",objectedit.mostCurrent._listobjects,"listsButtonAdd",objectedit.mostCurrent._listsbuttonadd,"listsButtonClose",objectedit.mostCurrent._listsbuttonclose,"listsLabelInfo",objectedit.mostCurrent._listslabelinfo,"listsTabPanel",objectedit.mostCurrent._liststabpanel,"LocationService",Debug.moduleToString(xevolution.vrcg.devdemov2400.locationservice.class),"Logs",Debug.moduleToString(xevolution.vrcg.devdemov2400.logs.class),"Main",Debug.moduleToString(xevolution.vrcg.devdemov2400.main.class),"mainActiveUser",objectedit.mostCurrent._mainactiveuser,"mainLabelOptLists",objectedit.mostCurrent._mainlabeloptlists,"mainLogo",objectedit.mostCurrent._mainlogo,"MainMenu",Debug.moduleToString(xevolution.vrcg.devdemov2400.mainmenu.class),"MapsActivity",Debug.moduleToString(xevolution.vrcg.devdemov2400.mapsactivity.class),"MenuPanel",objectedit.mostCurrent._menupanel,"MenuPanelButtomTwo",objectedit.mostCurrent._menupanelbuttomtwo,"MenuPanelButtonFour",objectedit.mostCurrent._menupanelbuttonfour,"MenuPanelButtonList",objectedit.mostCurrent._menupanelbuttonlist,"MenuPanelButtonOne",objectedit.mostCurrent._menupanelbuttonone,"MenuPanelButtonThree",objectedit.mostCurrent._menupanelbuttonthree,"MenuPanelPagesTitle",objectedit.mostCurrent._menupanelpagestitle,"NewSync",Debug.moduleToString(xevolution.vrcg.devdemov2400.newsync.class),"noRecordsLabel",objectedit.mostCurrent._norecordslabel,"noRecordsPanel",objectedit.mostCurrent._norecordspanel,"notas",Debug.moduleToString(xevolution.vrcg.devdemov2400.notas.class),"objectCode",objectedit.mostCurrent._objectcode,"objectContractDaysNotice",objectedit.mostCurrent._objectcontractdaysnotice,"objectContractDaysPeriod",objectedit.mostCurrent._objectcontractdaysperiod,"objectContractDuration",objectedit.mostCurrent._objectcontractduration,"objectContractEnd",objectedit.mostCurrent._objectcontractend,"objectContractHourPeriod",objectedit.mostCurrent._objectcontracthourperiod,"objectContractHours",objectedit.mostCurrent._objectcontracthours,"objectContractName",objectedit.mostCurrent._objectcontractname,"objectContractPeriod",objectedit.mostCurrent._objectcontractperiod,"objectContractStart",objectedit.mostCurrent._objectcontractstart,"objectDocumentsViewPanel",objectedit.mostCurrent._objectdocumentsviewpanel,"ObjectEditSelectedName",objectedit.mostCurrent._objecteditselectedname,"objectListView",objectedit.mostCurrent._objectlistview,"objectNotes",objectedit.mostCurrent._objectnotes,"ObjectParent",objectedit.mostCurrent._objectparent,"objectPropertyListView",objectedit.mostCurrent._objectpropertylistview,"Objects",Debug.moduleToString(xevolution.vrcg.devdemov2400.objects.class),"objectsDocumentsViewPanel",objectedit.mostCurrent._objectsdocumentsviewpanel,"objectsListViewPanel",objectedit.mostCurrent._objectslistviewpanel,"objectTagcode",objectedit.mostCurrent._objecttagcode,"objectType",objectedit.mostCurrent._objecttype,"objectWHItemsCheck",objectedit.mostCurrent._objectwhitemscheck,"objectWHItemsTaken",objectedit.mostCurrent._objectwhitemstaken,"objectWHName",objectedit.mostCurrent._objectwhname,"objGV2LabelCodInterno",objectedit.mostCurrent._objgv2labelcodinterno,"objGV2LabelObs",objectedit.mostCurrent._objgv2labelobs,"objGV2LabelRef",objectedit.mostCurrent._objgv2labelref,"objGV2LabelRelacao",objectedit.mostCurrent._objgv2labelrelacao,"objGV2LabelTipoObj",objectedit.mostCurrent._objgv2labeltipoobj,"ObjParent",objectedit.mostCurrent._objparent,"ObjRequests",objectedit.mostCurrent._objrequests,"ObjRequestsNotToday",objectedit.mostCurrent._objrequestsnottoday,"Panel1",objectedit.mostCurrent._panel1,"pnlCurrent",objectedit.mostCurrent._pnlcurrent,"pnlCurrentProp",objectedit.mostCurrent._pnlcurrentprop,"pnlGroupCurrenIndex",objectedit._pnlgroupcurrenindex,"pnlGroupCurrenPropIndex",objectedit._pnlgroupcurrenpropindex,"pnlGroupExpanded",objectedit.mostCurrent._pnlgroupexpanded,"pnlGroupExpanded2",objectedit.mostCurrent._pnlgroupexpanded2,"pnlGroupExpandedProp",objectedit.mostCurrent._pnlgroupexpandedprop,"pnlGroupTitle",objectedit.mostCurrent._pnlgrouptitle,"pnlGroupTitle2",objectedit.mostCurrent._pnlgrouptitle2,"pnlGroupTitleProp",objectedit.mostCurrent._pnlgrouptitleprop,"Report",Debug.moduleToString(xevolution.vrcg.devdemov2400.report.class),"ReportView",Debug.moduleToString(xevolution.vrcg.devdemov2400.reportview.class),"requests3",Debug.moduleToString(xevolution.vrcg.devdemov2400.requests3.class),"ShareCode",Debug.moduleToString(xevolution.vrcg.devdemov2400.sharecode.class),"ShowImage",objectedit.mostCurrent._showimage,"SignatureCapture",Debug.moduleToString(xevolution.vrcg.devdemov2400.signaturecapture.class),"Starter",Debug.moduleToString(xevolution.vrcg.devdemov2400.starter.class),"Structures",Debug.moduleToString(xevolution.vrcg.devdemov2400.structures.class),"TasksCL2",Debug.moduleToString(xevolution.vrcg.devdemov2400.taskscl2.class),"ThisObjectType",objectedit.mostCurrent._thisobjecttype,"TypeAddressList",objectedit.mostCurrent._typeaddresslist,"TypeContactsList",objectedit.mostCurrent._typecontactslist,"TypeDayPeriod",objectedit.mostCurrent._typedayperiod,"TypePeriodicity",objectedit.mostCurrent._typeperiodicity,"Types",Debug.moduleToString(xevolution.vrcg.devdemov2400.types.class),"UpdateService",Debug.moduleToString(xevolution.vrcg.devdemov2400.updateservice.class),"User",Debug.moduleToString(xevolution.vrcg.devdemov2400.user.class),"UserService",Debug.moduleToString(xevolution.vrcg.devdemov2400.userservice.class),"Utils",Debug.moduleToString(xevolution.vrcg.devdemov2400.utils.class),"w0",objectedit.mostCurrent._w0,"w1",objectedit.mostCurrent._w1,"w2",objectedit.mostCurrent._w2,"w3",objectedit.mostCurrent._w3,"w4",objectedit.mostCurrent._w4,"w5",objectedit.mostCurrent._w5,"w6",objectedit.mostCurrent._w6,"w7",objectedit.mostCurrent._w7,"WareHousePanel",objectedit.mostCurrent._warehousepanel,"xui",objectedit.mostCurrent._xui,"XUIViewsUtils",Debug.moduleToString(xevolution.vrcg.devdemov2400.xuiviewsutils.class)};
}
}