
package xevolution.vrcg.devdemov2400;

import java.io.IOException;
import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.pc.PCBA;
import anywheresoftware.b4a.pc.RDebug;
import anywheresoftware.b4a.pc.RemoteObject;
import anywheresoftware.b4a.pc.RDebug.IRemote;
import anywheresoftware.b4a.pc.Debug;
import anywheresoftware.b4a.pc.B4XTypes.B4XClass;
import anywheresoftware.b4a.pc.B4XTypes.DeviceClass;

public class requests3 implements IRemote{
	public static requests3 mostCurrent;
	public static RemoteObject processBA;
    public static boolean processGlobalsRun;
    public static RemoteObject myClass;
    public static RemoteObject remoteMe;
	public requests3() {
		mostCurrent = this;
	}
    public RemoteObject getRemoteMe() {
        return remoteMe;    
    }
    
	public static void main (String[] args) throws Exception {
		new RDebug(args[0], Integer.parseInt(args[1]), Integer.parseInt(args[2]), args[3]);
		RDebug.INSTANCE.waitForTask();

	}
    static {
        anywheresoftware.b4a.pc.RapidSub.moduleToObject.put(new B4XClass("requests3"), "xevolution.vrcg.devdemov2400.requests3");
	}

public boolean isSingleton() {
		return true;
	}
     public static RemoteObject getObject() {
		return myClass;
	 }

	public RemoteObject activityBA;
	public RemoteObject _activity;
    private PCBA pcBA;

	public PCBA create(Object[] args) throws ClassNotFoundException{
		processBA = (RemoteObject) args[1];
		activityBA = (RemoteObject) args[2];
		_activity = (RemoteObject) args[3];
        anywheresoftware.b4a.keywords.Common.Density = (Float)args[4];
        remoteMe = (RemoteObject) args[5];
		pcBA = new PCBA(this, requests3.class);
        main_subs_0.initializeProcessGlobals();
		return pcBA;
	}
public static RemoteObject __c = RemoteObject.declareNull("anywheresoftware.b4a.keywords.Common");
public static RemoteObject _device = RemoteObject.declareNull("anywheresoftware.b4a.phone.Phone");
public static RemoteObject _tilesource = RemoteObject.createImmutable("");
public static RemoteObject _zoomlevel = RemoteObject.createImmutable(0);
public static RemoteObject _markers = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _mapfirsttime = RemoteObject.createImmutable(false);
public static RemoteObject _mypositionlat = RemoteObject.createImmutable("");
public static RemoteObject _mypositionlon = RemoteObject.createImmutable("");
public static RemoteObject _currenttabpage = RemoteObject.createImmutable(0);
public static RemoteObject _infodatawindows = RemoteObject.createImmutable(false);
public static RemoteObject _icon = RemoteObject.declareNull("anywheresoftware.b4a.objects.drawable.BitmapDrawable");
public static RemoteObject _xui = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper.XUI");
public static RemoteObject _tilesourcespinner = RemoteObject.declareNull("anywheresoftware.b4a.objects.SpinnerWrapper");
public static RemoteObject _isfiltered = RemoteObject.createImmutable(false);
public static RemoteObject _filterstartdate = RemoteObject.createImmutable("");
public static RemoteObject _filterenddate = RemoteObject.createImmutable("");
public static RemoteObject _filtertasks = RemoteObject.createImmutable(0);
public static RemoteObject _filterentity = RemoteObject.createImmutable(0);
public static RemoteObject _filterroute = RemoteObject.createImmutable(0);
public static RemoteObject _filterstates = RemoteObject.createImmutable(0);
public static RemoteObject _filtertyperequests = RemoteObject.createImmutable(0);
public static RemoteObject _bloco30 = RemoteObject.createImmutable(0);
public static RemoteObject _listtyperequests = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _liststates = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _listentities = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _listtasks = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _listroutes = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _buttonuserunavailable = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _mapuserposition = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _colortabpanel = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _buttonactiontransport = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _buttonappalert = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _buttonappnetwork = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _labelappinfo = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelcopyright = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labeldatetime = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelversion = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listsbasepanel = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _listsbottomline = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _listsbottompanel = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _listsbuttonclose = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _listsbuttonfilter = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _listslabelinfo = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _liststabpanel = RemoteObject.declareNull("anywheresoftware.b4a.objects.TabStripViewPager");
public static RemoteObject _liststopbar = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _mainlabeloptlists = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _mainlogo = RemoteObject.declareNull("anywheresoftware.b4a.objects.ImageViewWrapper");
public static RemoteObject _maintopline = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _idialogreqtypeobject = RemoteObject.createImmutable(0);
public static RemoteObject _idialogreqzone = RemoteObject.createImmutable(0);
public static RemoteObject _idialogreqstatus = RemoteObject.createImmutable(0);
public static RemoteObject _idialogreqregion = RemoteObject.createImmutable(0);
public static RemoteObject _idialogreqlocal = RemoteObject.createImmutable(0);
public static RemoteObject _idialogreqwithrequests = RemoteObject.createImmutable(0);
public static RemoteObject _sdialogreqname = RemoteObject.createImmutable("");
public static RemoteObject _sdialogreqaddress = RemoteObject.createImmutable("");
public static RemoteObject _searchfilter = RemoteObject.createImmutable("");
public static RemoteObject _regionslist = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _typeobjectslist = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _localslist = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _reqrequests = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _reqrequestsnottoday = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _itemscounter = RemoteObject.createImmutable(0);
public static RemoteObject _listrequestsbuttonmap = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _mapbaselist = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _mapbasepanel = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _mapzoomdown = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _mapzoomup = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _listrequests = RemoteObject.declareNull("b4a.example3.customlistview");
public static RemoteObject _listsrequestsmap = RemoteObject.declareNull("b4a.example3.customlistview");
public static RemoteObject _pnlgrouptitle = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _pnlgroupdata = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _listitemtodayrequests = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listitemreference = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listitemdatetime = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listitemcontact = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listitemfullname = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listitemstatus = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listbutmap = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _listitemobject = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listitemobjecttask = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listitemobjectexecution = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listbutobjectaction = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _listitemobjectstatus = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listitemobjectstatusicon = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _currentgroupitem = RemoteObject.createImmutable(0);
public static RemoteObject _pnlgroupcurrenindex = RemoteObject.createImmutable(0);
public static RemoteObject _clicklabel = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _showlistpedidosmap = RemoteObject.createImmutable(false);
public static RemoteObject _editsearch = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _butsearch = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _currentindexpanel = RemoteObject.createImmutable(0);
public static RemoteObject _currentidpanel = RemoteObject.createImmutable(0);
public static RemoteObject _labelbuttontitleaction = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelreferenciasdescritivos = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelstatus = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _requestsoptionspopmenu = RemoteObject.declareNull("com.jakes.menuonviews.menuonanyview");
public static RemoteObject _currentlineitem = RemoteObject.createImmutable(0);
public static RemoteObject _totallineitems = RemoteObject.createImmutable(0);
public static RemoteObject _listitemobjectnumber = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listbutmore = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _listitemobjectdatetime = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listitemobjectreference = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _pnlgroupdatasub = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _pnlgroupdatalist = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.expandedlistview");
public static RemoteObject _currentpage = RemoteObject.createImmutable(0);
public static RemoteObject _pages = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _listrequestsitem = RemoteObject.declareNull("b4a.example3.customlistview");
public static RemoteObject _clabuttonoptions = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _claitem_g1 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _claitembutton_1 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _claitembutton_2 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _claitem_g2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _claitem_g3 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _claitem_g4 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _claitem_g5 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _claitem_g6 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _claitem_g7 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listitemtype = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listitem_notes = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listitem_status = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listitem_datetime = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listitem_entity = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listitem_cloud = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listbutcompare = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _listitem_typerequest = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listrequestsitemsecond = RemoteObject.declareNull("b4a.example3.customlistview");
public static RemoteObject _claitembuttonbr_svr2 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _claitembuttonbr_svr2_a = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _cla_br_ksvrf2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.FloatLabeledEditTextWrapper");
public static RemoteObject _cla_br_ksvrf2_a = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _cla_br_ksvri2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.FloatLabeledEditTextWrapper");
public static RemoteObject _cla_br_ksvri2_a = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _cla_br_ksvri1_a = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _cla_br_ksvri1 = RemoteObject.declareNull("anywheresoftware.b4a.objects.FloatLabeledEditTextWrapper");
public static RemoteObject _cla_br_ksvrf1 = RemoteObject.declareNull("anywheresoftware.b4a.objects.FloatLabeledEditTextWrapper");
public static RemoteObject _cla_br_ksvrf1_a = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _claitembuttonbr_svr1 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _claitembuttonbr_svr1_a = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _claitembuttonbr_init_a = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _claitembuttonbr_init = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _cla_br_obs = RemoteObject.declareNull("anywheresoftware.b4a.objects.FloatLabeledEditTextWrapper");
public static RemoteObject _cla_br_obs_a = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _cla_br_kmi_a = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _cla_br_kmi = RemoteObject.declareNull("anywheresoftware.b4a.objects.FloatLabeledEditTextWrapper");
public static RemoteObject _cla_br_car = RemoteObject.declareNull("anywheresoftware.b4a.objects.FloatLabeledEditTextWrapper");
public static RemoteObject _cla_br_car_a = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _cla_br_kmf_a = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _cla_br_kmf = RemoteObject.declareNull("anywheresoftware.b4a.objects.FloatLabeledEditTextWrapper");
public static RemoteObject _cla_br_e1 = RemoteObject.declareNull("anywheresoftware.b4a.objects.FloatLabeledEditTextWrapper");
public static RemoteObject _cla_br_s1 = RemoteObject.declareNull("anywheresoftware.b4a.objects.FloatLabeledEditTextWrapper");
public static RemoteObject _cla_br_e2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.FloatLabeledEditTextWrapper");
public static RemoteObject _cla_br_s2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.FloatLabeledEditTextWrapper");
public static RemoteObject _cla_br_e3 = RemoteObject.declareNull("anywheresoftware.b4a.objects.FloatLabeledEditTextWrapper");
public static RemoteObject _cla_br_s3 = RemoteObject.declareNull("anywheresoftware.b4a.objects.FloatLabeledEditTextWrapper");
public static RemoteObject _claitembuttonbr = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _claitembuttonbr_a = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _claitembuttonx_a = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _b4xstatebutton1 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _b4xstatebutton2 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _b4xstatebutton3 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _b4xstatebutton4 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _b4xstatebutton5 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _b4xstatebutton6 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _b4xstatebutton7 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _b4xstatebutton14 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _b4xstatebutton13 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _b4xstatebutton21 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _b4xstatebutton20 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _b4xstatebutton19 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _b4xstatebutton12 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _b4xstatebutton11 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _b4xstatebutton18 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _b4xstatebutton17 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _b4xstatebutton10 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _b4xstatebutton9 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _b4xstatebutton16 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _b4xstatebutton15 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _b4xstatebutton8 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _b4xstatebutton22 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _b4xstatebutton23 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _b4xstatebutton24 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _b4xstatebutton25 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _b4xstatebutton26 = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.b4xstatebutton");
public static RemoteObject _view_requests_listview = RemoteObject.createImmutable("");
public static RemoteObject _view_requests_listviewrequest = RemoteObject.createImmutable("");
public static RemoteObject _view_requests_listviewrequest2 = RemoteObject.createImmutable("");
public static RemoteObject _view_requests_mapview = RemoteObject.createImmutable("");
public static RemoteObject _buttonactionpause = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _currentfilter = RemoteObject.createImmutable("");
public static RemoteObject _mainactiveuser = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _gmap = RemoteObject.declareNull("anywheresoftware.b4a.objects.MapFragmentWrapper.GoogleMapWrapper");
public static RemoteObject _mapdata = RemoteObject.declareNull("anywheresoftware.b4a.objects.MapFragmentWrapper");
public static RemoteObject _mapmarker = RemoteObject.declareNull("anywheresoftware.b4a.objects.MapFragmentWrapper.MarkerWrapper");
public static RemoteObject _listsbuttonpull = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _listbutnote = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _butquickaction = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _listitem_favorite = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listsbuttonfavorites = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _listitem_desc02 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listitem_desc01 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listaprincipalclickitem = RemoteObject.createImmutable(0);
public static RemoteObject _listviewdevice3panel = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _listviewrequestdevice3panel = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _listviewrequest2device3panel = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _listitemclickindex = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listitem_desc00 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _subitemimage = RemoteObject.declareNull("anywheresoftware.b4a.objects.ImageViewWrapper");
public static RemoteObject _lockpanel = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _grandactive_instance = RemoteObject.createImmutable("");
public static RemoteObject _lockpanelinfo = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _current_limit = RemoteObject.createImmutable(0);
public static RemoteObject _current_offset = RemoteObject.createImmutable(0);
public static RemoteObject _next_current_limit = RemoteObject.createImmutable(0);
public static RemoteObject _next_offset = RemoteObject.createImmutable(0);
public static RemoteObject _currenttotalitems = RemoteObject.createImmutable(0);
public static RemoteObject _selectedtagcode = RemoteObject.createImmutable("");
public static RemoteObject _selectedrequestdata = RemoteObject.declareNull("xevolution.vrcg.devdemov2400.types._requestdata");
public static RemoteObject _listitemnumber = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _data_intervencao = RemoteObject.declareNull("anywheresoftware.b4a.objects.FloatLabeledEditTextWrapper");
public static RemoteObject _hora_intervencao = RemoteObject.declareNull("anywheresoftware.b4a.objects.FloatLabeledEditTextWrapper");
public static RemoteObject _tasklist2dup = RemoteObject.declareNull("b4a.example3.customlistview");
public static RemoteObject _botaodatadup = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _botaohoradup = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _dupitemcheck = RemoteObject.declareNull("anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper");
public static RemoteObject _dupitemlabel = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _listitemtechnical = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _globalscanreturn = RemoteObject.createImmutable(false);
public static RemoteObject _dateutils = RemoteObject.declareNull("b4a.example.dateutils");
public static RemoteObject _encoding = RemoteObject.declareNull("b4a.example.encoding");
public static RemoteObject _esc_pos = RemoteObject.declareNull("b4a.example.esc_pos");
public static xevolution.vrcg.devdemov2400.main _main = null;
public static xevolution.vrcg.devdemov2400.starter _starter = null;
public static xevolution.vrcg.devdemov2400.comms _comms = null;
public static xevolution.vrcg.devdemov2400.utils _utils = null;
public static xevolution.vrcg.devdemov2400.dbstructures _dbstructures = null;
public static xevolution.vrcg.devdemov2400.sharecode _sharecode = null;
public static xevolution.vrcg.devdemov2400.mainmenu _mainmenu = null;
public static xevolution.vrcg.devdemov2400.imageedit _imageedit = null;
public static xevolution.vrcg.devdemov2400.checklist3 _checklist3 = null;
public static xevolution.vrcg.devdemov2400.locationservice _locationservice = null;
public static xevolution.vrcg.devdemov2400.dataupdate _dataupdate = null;
public static xevolution.vrcg.devdemov2400.alerts _alerts = null;
public static xevolution.vrcg.devdemov2400.backgroundupdateservice _backgroundupdateservice = null;
public static xevolution.vrcg.devdemov2400.barcodescanner _barcodescanner = null;
public static xevolution.vrcg.devdemov2400.cameraactivity _cameraactivity = null;
public static xevolution.vrcg.devdemov2400.cameraactivity_innershot _cameraactivity_innershot = null;
public static xevolution.vrcg.devdemov2400.cameraactivity2 _cameraactivity2 = null;
public static xevolution.vrcg.devdemov2400.checklistnew _checklistnew = null;
public static xevolution.vrcg.devdemov2400.common _common = null;
public static xevolution.vrcg.devdemov2400.consts _consts = null;
public static xevolution.vrcg.devdemov2400.dbutils _dbutils = null;
public static xevolution.vrcg.devdemov2400.helpdescriptors _helpdescriptors = null;
public static xevolution.vrcg.devdemov2400.logs _logs = null;
public static xevolution.vrcg.devdemov2400.mapsactivity _mapsactivity = null;
public static xevolution.vrcg.devdemov2400.newsync _newsync = null;
public static xevolution.vrcg.devdemov2400.notas _notas = null;
public static xevolution.vrcg.devdemov2400.objectedit _objectedit = null;
public static xevolution.vrcg.devdemov2400.objects _objects = null;
public static xevolution.vrcg.devdemov2400.report _report = null;
public static xevolution.vrcg.devdemov2400.reportview _reportview = null;
public static xevolution.vrcg.devdemov2400.signaturecapture _signaturecapture = null;
public static xevolution.vrcg.devdemov2400.structures _structures = null;
public static xevolution.vrcg.devdemov2400.taskscl2 _taskscl2 = null;
public static xevolution.vrcg.devdemov2400.types _types = null;
public static xevolution.vrcg.devdemov2400.updateservice _updateservice = null;
public static xevolution.vrcg.devdemov2400.user _user = null;
public static xevolution.vrcg.devdemov2400.userservice _userservice = null;
public static xevolution.vrcg.devdemov2400.httputils2service _httputils2service = null;
public static xevolution.vrcg.devdemov2400.xuiviewsutils _xuiviewsutils = null;
  public Object[] GetGlobals() {
		return new Object[] {"Activity",requests3.mostCurrent._activity,"Alerts",Debug.moduleToString(xevolution.vrcg.devdemov2400.alerts.class),"B4XStateButton1",requests3.mostCurrent._b4xstatebutton1,"B4XStateButton10",requests3.mostCurrent._b4xstatebutton10,"B4XStateButton11",requests3.mostCurrent._b4xstatebutton11,"B4XStateButton12",requests3.mostCurrent._b4xstatebutton12,"B4XStateButton13",requests3.mostCurrent._b4xstatebutton13,"B4XStateButton14",requests3.mostCurrent._b4xstatebutton14,"B4XStateButton15",requests3.mostCurrent._b4xstatebutton15,"B4XStateButton16",requests3.mostCurrent._b4xstatebutton16,"B4XStateButton17",requests3.mostCurrent._b4xstatebutton17,"B4XStateButton18",requests3.mostCurrent._b4xstatebutton18,"B4XStateButton19",requests3.mostCurrent._b4xstatebutton19,"B4XStateButton2",requests3.mostCurrent._b4xstatebutton2,"B4XStateButton20",requests3.mostCurrent._b4xstatebutton20,"B4XStateButton21",requests3.mostCurrent._b4xstatebutton21,"B4XStateButton22",requests3.mostCurrent._b4xstatebutton22,"B4XStateButton23",requests3.mostCurrent._b4xstatebutton23,"B4XStateButton24",requests3.mostCurrent._b4xstatebutton24,"B4XStateButton25",requests3.mostCurrent._b4xstatebutton25,"B4XStateButton26",requests3.mostCurrent._b4xstatebutton26,"B4XStateButton3",requests3.mostCurrent._b4xstatebutton3,"B4XStateButton4",requests3.mostCurrent._b4xstatebutton4,"B4XStateButton5",requests3.mostCurrent._b4xstatebutton5,"B4XStateButton6",requests3.mostCurrent._b4xstatebutton6,"B4XStateButton7",requests3.mostCurrent._b4xstatebutton7,"B4XStateButton8",requests3.mostCurrent._b4xstatebutton8,"B4XStateButton9",requests3.mostCurrent._b4xstatebutton9,"BackgroundUpdateService",Debug.moduleToString(xevolution.vrcg.devdemov2400.backgroundupdateservice.class),"BarcodeScanner",Debug.moduleToString(xevolution.vrcg.devdemov2400.barcodescanner.class),"Bloco30",requests3._bloco30,"BotaoDataDup",requests3.mostCurrent._botaodatadup,"BotaoHoraDup",requests3.mostCurrent._botaohoradup,"butQuickAction",requests3.mostCurrent._butquickaction,"butSearch",requests3.mostCurrent._butsearch,"ButtonActionPause",requests3.mostCurrent._buttonactionpause,"ButtonActionTransport",requests3.mostCurrent._buttonactiontransport,"ButtonAppAlert",requests3.mostCurrent._buttonappalert,"ButtonAppNetwork",requests3.mostCurrent._buttonappnetwork,"ButtonUserUnavailable",requests3.mostCurrent._buttonuserunavailable,"CameraActivity",Debug.moduleToString(xevolution.vrcg.devdemov2400.cameraactivity.class),"CameraActivity_InnerShot",Debug.moduleToString(xevolution.vrcg.devdemov2400.cameraactivity_innershot.class),"CameraActivity2",Debug.moduleToString(xevolution.vrcg.devdemov2400.cameraactivity2.class),"CheckList3",Debug.moduleToString(xevolution.vrcg.devdemov2400.checklist3.class),"CheckListNew",Debug.moduleToString(xevolution.vrcg.devdemov2400.checklistnew.class),"CLA_BR_CAR",requests3.mostCurrent._cla_br_car,"CLA_BR_CAR_A",requests3.mostCurrent._cla_br_car_a,"CLA_BR_E1",requests3.mostCurrent._cla_br_e1,"CLA_BR_E2",requests3.mostCurrent._cla_br_e2,"CLA_BR_E3",requests3.mostCurrent._cla_br_e3,"CLA_BR_KMF",requests3.mostCurrent._cla_br_kmf,"CLA_BR_KMF_A",requests3.mostCurrent._cla_br_kmf_a,"CLA_BR_KMI",requests3.mostCurrent._cla_br_kmi,"CLA_BR_KMI_A",requests3.mostCurrent._cla_br_kmi_a,"CLA_BR_KSVRF1",requests3.mostCurrent._cla_br_ksvrf1,"CLA_BR_KSVRF1_A",requests3.mostCurrent._cla_br_ksvrf1_a,"CLA_BR_KSVRF2",requests3.mostCurrent._cla_br_ksvrf2,"CLA_BR_KSVRF2_A",requests3.mostCurrent._cla_br_ksvrf2_a,"CLA_BR_KSVRI1",requests3.mostCurrent._cla_br_ksvri1,"CLA_BR_KSVRI1_A",requests3.mostCurrent._cla_br_ksvri1_a,"CLA_BR_KSVRI2",requests3.mostCurrent._cla_br_ksvri2,"CLA_BR_KSVRI2_A",requests3.mostCurrent._cla_br_ksvri2_a,"CLA_BR_OBS",requests3.mostCurrent._cla_br_obs,"CLA_BR_OBS_A",requests3.mostCurrent._cla_br_obs_a,"CLA_BR_S1",requests3.mostCurrent._cla_br_s1,"CLA_BR_S2",requests3.mostCurrent._cla_br_s2,"CLA_BR_S3",requests3.mostCurrent._cla_br_s3,"CLAButtonOptions",requests3.mostCurrent._clabuttonoptions,"CLAItem_G1",requests3.mostCurrent._claitem_g1,"CLAItem_G2",requests3.mostCurrent._claitem_g2,"CLAItem_G3",requests3.mostCurrent._claitem_g3,"CLAItem_G4",requests3.mostCurrent._claitem_g4,"CLAItem_G5",requests3.mostCurrent._claitem_g5,"CLAItem_G6",requests3.mostCurrent._claitem_g6,"CLAItem_G7",requests3.mostCurrent._claitem_g7,"CLAItemButton_1",requests3.mostCurrent._claitembutton_1,"CLAItemButton_2",requests3.mostCurrent._claitembutton_2,"CLAItemButtonBR",requests3.mostCurrent._claitembuttonbr,"CLAItemButtonBR_A",requests3.mostCurrent._claitembuttonbr_a,"CLAItemButtonBR_INIT",requests3.mostCurrent._claitembuttonbr_init,"CLAItemButtonBR_INIT_A",requests3.mostCurrent._claitembuttonbr_init_a,"CLAItemButtonBR_SVR1",requests3.mostCurrent._claitembuttonbr_svr1,"CLAItemButtonBR_SVR1_A",requests3.mostCurrent._claitembuttonbr_svr1_a,"CLAItemButtonBR_SVR2",requests3.mostCurrent._claitembuttonbr_svr2,"CLAItemButtonBR_SVR2_A",requests3.mostCurrent._claitembuttonbr_svr2_a,"CLAItemButtonX_A",requests3.mostCurrent._claitembuttonx_a,"ClickLabel",requests3.mostCurrent._clicklabel,"ColorTabPanel",requests3.mostCurrent._colortabpanel,"Common",Debug.moduleToString(xevolution.vrcg.devdemov2400.common.class),"Comms",Debug.moduleToString(xevolution.vrcg.devdemov2400.comms.class),"Consts",Debug.moduleToString(xevolution.vrcg.devdemov2400.consts.class),"current_limit",requests3._current_limit,"current_offset",requests3._current_offset,"CurrentFilter",requests3.mostCurrent._currentfilter,"CurrentGroupItem",requests3._currentgroupitem,"CurrentIDPanel",requests3._currentidpanel,"CurrentIndexPanel",requests3._currentindexpanel,"CurrentLineItem",requests3._currentlineitem,"CurrentPage",requests3._currentpage,"CurrentTabPage",requests3._currenttabpage,"CurrentTotalItems",requests3._currenttotalitems,"data_Intervencao",requests3.mostCurrent._data_intervencao,"DataUpdate",Debug.moduleToString(xevolution.vrcg.devdemov2400.dataupdate.class),"DateUtils",requests3.mostCurrent._dateutils,"DBStructures",Debug.moduleToString(xevolution.vrcg.devdemov2400.dbstructures.class),"DBUtils",Debug.moduleToString(xevolution.vrcg.devdemov2400.dbutils.class),"Device",requests3._device,"dupItemCheck",requests3.mostCurrent._dupitemcheck,"dupItemLabel",requests3.mostCurrent._dupitemlabel,"EditSearch",requests3.mostCurrent._editsearch,"Encoding",requests3.mostCurrent._encoding,"ESC_POS",requests3.mostCurrent._esc_pos,"FilterEndDate",requests3.mostCurrent._filterenddate,"FilterEntity",requests3._filterentity,"FilterRoute",requests3._filterroute,"FilterStartDate",requests3.mostCurrent._filterstartdate,"FilterStates",requests3._filterstates,"FilterTasks",requests3._filtertasks,"FilterTypeRequests",requests3._filtertyperequests,"GlobalScanReturn",requests3._globalscanreturn,"gmap",requests3.mostCurrent._gmap,"GRANDACTIVE_INSTANCE",requests3.mostCurrent._grandactive_instance,"HelpDescriptors",Debug.moduleToString(xevolution.vrcg.devdemov2400.helpdescriptors.class),"hora_intervencao",requests3.mostCurrent._hora_intervencao,"HttpUtils2Service",Debug.moduleToString(xevolution.vrcg.devdemov2400.httputils2service.class),"Icon",requests3.mostCurrent._icon,"iDialogReqLocal",requests3._idialogreqlocal,"iDialogReqRegion",requests3._idialogreqregion,"iDialogReqStatus",requests3._idialogreqstatus,"iDialogReqTypeObject",requests3._idialogreqtypeobject,"iDialogReqWithRequests",requests3._idialogreqwithrequests,"iDialogReqZone",requests3._idialogreqzone,"ImageEdit",Debug.moduleToString(xevolution.vrcg.devdemov2400.imageedit.class),"InfoDataWindows",requests3._infodatawindows,"IsFiltered",requests3._isfiltered,"ItemsCounter",requests3._itemscounter,"LabelAppInfo",requests3.mostCurrent._labelappinfo,"LabelButtonTitleAction",requests3.mostCurrent._labelbuttontitleaction,"LabelCopyright",requests3.mostCurrent._labelcopyright,"LabelDateTime",requests3.mostCurrent._labeldatetime,"LabelReferenciasDescritivos",requests3.mostCurrent._labelreferenciasdescritivos,"LabelStatus",requests3.mostCurrent._labelstatus,"LabelVersion",requests3.mostCurrent._labelversion,"ListaPrincipalClickItem",requests3._listaprincipalclickitem,"listButCompare",requests3.mostCurrent._listbutcompare,"listButMap",requests3.mostCurrent._listbutmap,"listButMore",requests3.mostCurrent._listbutmore,"listButNote",requests3.mostCurrent._listbutnote,"listButObjectAction",requests3.mostCurrent._listbutobjectaction,"ListEntities",requests3.mostCurrent._listentities,"ListItem_Cloud",requests3.mostCurrent._listitem_cloud,"ListItem_Datetime",requests3.mostCurrent._listitem_datetime,"ListItem_Desc00",requests3.mostCurrent._listitem_desc00,"ListItem_Desc01",requests3.mostCurrent._listitem_desc01,"ListItem_Desc02",requests3.mostCurrent._listitem_desc02,"ListItem_Entity",requests3.mostCurrent._listitem_entity,"ListItem_Favorite",requests3.mostCurrent._listitem_favorite,"ListItem_Notes",requests3.mostCurrent._listitem_notes,"ListItem_Status",requests3.mostCurrent._listitem_status,"ListItem_TypeRequest",requests3.mostCurrent._listitem_typerequest,"ListItemClickIndex",requests3.mostCurrent._listitemclickindex,"ListItemContact",requests3.mostCurrent._listitemcontact,"ListItemDatetime",requests3.mostCurrent._listitemdatetime,"ListItemFullName",requests3.mostCurrent._listitemfullname,"ListItemNumber",requests3.mostCurrent._listitemnumber,"ListItemObject",requests3.mostCurrent._listitemobject,"ListItemObjectDateTime",requests3.mostCurrent._listitemobjectdatetime,"ListItemObjectExecution",requests3.mostCurrent._listitemobjectexecution,"ListItemObjectNumber",requests3.mostCurrent._listitemobjectnumber,"ListItemObjectReference",requests3.mostCurrent._listitemobjectreference,"ListItemObjectStatus",requests3.mostCurrent._listitemobjectstatus,"ListItemObjectStatusIcon",requests3.mostCurrent._listitemobjectstatusicon,"ListItemObjectTask",requests3.mostCurrent._listitemobjecttask,"ListItemReference",requests3.mostCurrent._listitemreference,"ListItemStatus",requests3.mostCurrent._listitemstatus,"ListITemTechnical",requests3.mostCurrent._listitemtechnical,"ListItemTodayRequests",requests3.mostCurrent._listitemtodayrequests,"ListItemType",requests3.mostCurrent._listitemtype,"listRequests",requests3.mostCurrent._listrequests,"listRequestsButtonMap",requests3.mostCurrent._listrequestsbuttonmap,"listRequestsItem",requests3.mostCurrent._listrequestsitem,"listRequestsItemSecond",requests3.mostCurrent._listrequestsitemsecond,"ListRoutes",requests3.mostCurrent._listroutes,"listsBasePanel",requests3.mostCurrent._listsbasepanel,"listsBottomLine",requests3.mostCurrent._listsbottomline,"listsBottomPanel",requests3.mostCurrent._listsbottompanel,"listsButtonClose",requests3.mostCurrent._listsbuttonclose,"listsButtonFavorites",requests3.mostCurrent._listsbuttonfavorites,"listsButtonFilter",requests3.mostCurrent._listsbuttonfilter,"listsButtonPull",requests3.mostCurrent._listsbuttonpull,"listsLabelInfo",requests3.mostCurrent._listslabelinfo,"listsRequestsMap",requests3.mostCurrent._listsrequestsmap,"listsTabPanel",requests3.mostCurrent._liststabpanel,"ListStates",requests3.mostCurrent._liststates,"listsTopBar",requests3.mostCurrent._liststopbar,"ListTasks",requests3.mostCurrent._listtasks,"ListTypeRequests",requests3.mostCurrent._listtyperequests,"ListViewDevice3Panel",requests3.mostCurrent._listviewdevice3panel,"ListViewRequest2Device3Panel",requests3.mostCurrent._listviewrequest2device3panel,"ListViewRequestDevice3Panel",requests3.mostCurrent._listviewrequestdevice3panel,"LocalsList",requests3.mostCurrent._localslist,"LocationService",Debug.moduleToString(xevolution.vrcg.devdemov2400.locationservice.class),"LockPanel",requests3.mostCurrent._lockpanel,"LockPanelInfo",requests3.mostCurrent._lockpanelinfo,"Logs",Debug.moduleToString(xevolution.vrcg.devdemov2400.logs.class),"Main",Debug.moduleToString(xevolution.vrcg.devdemov2400.main.class),"mainActiveUser",requests3.mostCurrent._mainactiveuser,"mainLabelOptLists",requests3.mostCurrent._mainlabeloptlists,"mainLogo",requests3.mostCurrent._mainlogo,"MainMenu",Debug.moduleToString(xevolution.vrcg.devdemov2400.mainmenu.class),"mainTopLine",requests3.mostCurrent._maintopline,"mapBaseList",requests3.mostCurrent._mapbaselist,"mapBasePanel",requests3.mostCurrent._mapbasepanel,"mapData",requests3.mostCurrent._mapdata,"MapFirstTime",requests3._mapfirsttime,"mapMarker",requests3.mostCurrent._mapmarker,"MapsActivity",Debug.moduleToString(xevolution.vrcg.devdemov2400.mapsactivity.class),"mapUserPosition",requests3.mostCurrent._mapuserposition,"mapZoomDown",requests3.mostCurrent._mapzoomdown,"mapZoomUp",requests3.mostCurrent._mapzoomup,"Markers",requests3._markers,"MyPositionLat",requests3._mypositionlat,"MyPositionLon",requests3._mypositionlon,"NewSync",Debug.moduleToString(xevolution.vrcg.devdemov2400.newsync.class),"next_current_limit",requests3._next_current_limit,"next_offset",requests3._next_offset,"notas",Debug.moduleToString(xevolution.vrcg.devdemov2400.notas.class),"ObjectEdit",Debug.moduleToString(xevolution.vrcg.devdemov2400.objectedit.class),"Objects",Debug.moduleToString(xevolution.vrcg.devdemov2400.objects.class),"Pages",requests3.mostCurrent._pages,"pnlGroupCurrenIndex",requests3._pnlgroupcurrenindex,"pnlGroupData",requests3.mostCurrent._pnlgroupdata,"pnlGroupDataList",requests3.mostCurrent._pnlgroupdatalist,"pnlGroupDataSub",requests3.mostCurrent._pnlgroupdatasub,"pnlGroupTitle",requests3.mostCurrent._pnlgrouptitle,"RegionsList",requests3.mostCurrent._regionslist,"Report",Debug.moduleToString(xevolution.vrcg.devdemov2400.report.class),"ReportView",Debug.moduleToString(xevolution.vrcg.devdemov2400.reportview.class),"ReqRequests",requests3.mostCurrent._reqrequests,"ReqRequestsNotToday",requests3.mostCurrent._reqrequestsnottoday,"RequestsOptionsPopMenu",requests3.mostCurrent._requestsoptionspopmenu,"sDialogReqAddress",requests3.mostCurrent._sdialogreqaddress,"sDialogReqName",requests3.mostCurrent._sdialogreqname,"SearchFilter",requests3.mostCurrent._searchfilter,"SelectedRequestData",requests3.mostCurrent._selectedrequestdata,"SelectedTagcode",requests3.mostCurrent._selectedtagcode,"ShareCode",Debug.moduleToString(xevolution.vrcg.devdemov2400.sharecode.class),"ShowListPedidosMap",requests3._showlistpedidosmap,"SignatureCapture",Debug.moduleToString(xevolution.vrcg.devdemov2400.signaturecapture.class),"Starter",Debug.moduleToString(xevolution.vrcg.devdemov2400.starter.class),"Structures",Debug.moduleToString(xevolution.vrcg.devdemov2400.structures.class),"SubItemImage",requests3.mostCurrent._subitemimage,"TaskList2Dup",requests3.mostCurrent._tasklist2dup,"TasksCL2",Debug.moduleToString(xevolution.vrcg.devdemov2400.taskscl2.class),"TileSource",requests3._tilesource,"TileSourceSpinner",requests3.mostCurrent._tilesourcespinner,"TotalLineItems",requests3._totallineitems,"TypeObjectsList",requests3.mostCurrent._typeobjectslist,"Types",Debug.moduleToString(xevolution.vrcg.devdemov2400.types.class),"UpdateService",Debug.moduleToString(xevolution.vrcg.devdemov2400.updateservice.class),"User",Debug.moduleToString(xevolution.vrcg.devdemov2400.user.class),"UserService",Debug.moduleToString(xevolution.vrcg.devdemov2400.userservice.class),"Utils",Debug.moduleToString(xevolution.vrcg.devdemov2400.utils.class),"VIEW_requests_listview",requests3.mostCurrent._view_requests_listview,"VIEW_requests_listviewrequest",requests3.mostCurrent._view_requests_listviewrequest,"VIEW_requests_listviewrequest2",requests3.mostCurrent._view_requests_listviewrequest2,"VIEW_requests_mapview",requests3.mostCurrent._view_requests_mapview,"xui",requests3.mostCurrent._xui,"XUIViewsUtils",Debug.moduleToString(xevolution.vrcg.devdemov2400.xuiviewsutils.class),"ZoomLevel",requests3._zoomlevel};
}
}